#!/usr/bin/env node
// OpenCode 하네스 어댑터 — user-level **제거**(setup/user-install.mjs 의 installOpencode 역연산).
// uninstall = 머신에서 lively 셋업을 **영구 제거**. incognito(LIVELY_OFF, 일시 off)와 다르다.
//
// 하는 일(전부 idempotent · surgical · 백업 먼저):
//  (1) ~/.config/opencode/plugin/lively.js  ← 우리가 놓은 어댑터 파일만 삭제(같은 디렉터리의 사용자 플러그인 불가침).
//  (2) ~/.config/opencode/opencode.json     ← 우리가 넣은 키만 surgical 제거: `mcp.lively` 와
//        우리가 심은 permission 키(~/.lively/managed-opencode-permission.json 이 그 목록의 정본).
//        사용자 키(model·agent·다른 mcp·본인 permission)는 한 바이트도 안 건드린다.
//        ⚠ 주석이 든 .jsonc 등 JSON 으로 못 읽는 파일은 **건드리지 않는다** — 다시 쓰면 사용자 주석이 사라진다.
//  (3) ~/.config/opencode/AGENTS.md         ← install 이 센티넬로 머지한 org-context 블록만 제거(밖은 보존).
//        블록 제거 후 내용이 비면 파일 삭제(모두 백업 후).
//
// 공유 자산(~/.lively/*)은 여기서 안 지운다 — 공통 정리(setup/uninstall.mjs)가 담당.
// ⚠ `~/.claude/skills` 자동 로드는 opencode 의 기본 동작이라 우리가 끄지 않았고, 따라서 되돌릴 것도 없다
//   (#1519 결정: 스킬 격리 안 함).
//
// 사용법: node adapters/opencode/uninstall.mjs [--dry-run]
// 샌드박스/테스트: env LIVELY_HOME=<dir> 로 HOME 리다이렉트(라이브 보호). 미지정 시 os.homedir().

import { readFileSync, writeFileSync, existsSync, mkdirSync, copyFileSync, rmSync, rmdirSync, readdirSync, realpathSync } from "node:fs";
import { homedir } from "node:os";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const HOME = process.env.LIVELY_HOME || homedir();
const LIVELY = join(HOME, ".lively");
const OPENCODE = join(HOME, ".config", "opencode");

// install 과 동일한 AGENTS.md 센티넬(역연산이므로 정확히 일치해야 한다 — codex 와 같은 리터럴을 공유한다).
const AG_BEGIN = "<!-- >>> lively-managed org-context (auto-generated by workflow-std — do not edit) >>> -->";
const AG_END = "<!-- <<< lively-managed <<< -->";

const log = (s) => console.log(s);

function backup(path, name) {
  try {
    const dir = join(LIVELY, "backups");
    mkdirSync(dir, { recursive: true });
    if (existsSync(path)) copyFileSync(path, join(dir, name));
  } catch { /* 백업 실패해도 아래 편집은 surgical(비파괴) */ }
}

// (1) 플러그인 어댑터 제거 — 우리 파일 하나만. 디렉터리가 비면 정리(사용자 플러그인이 있으면 그대로 둔다).
export function removePlugin({ dry = false } = {}) {
  const dir = join(OPENCODE, "plugin");
  const f = join(dir, "lively.js");
  if (!existsSync(f)) { log("  · ~/.config/opencode/plugin/lively.js 없음 — 건너뜀"); return 0; }
  if (dry) { log("  [dry-run] ~/.config/opencode/plugin/lively.js 제거 예정"); return 1; }
  try { rmSync(f, { force: true }); } catch (e) { log(`  ⚠️ 어댑터 제거 실패: ${e.message}`); return 0; }
  try { if (readdirSync(dir).length === 0) rmdirSync(dir); } catch { /* 사용자 플러그인이 남아 있으면 보존 */ }
  log("  ✓ ~/.config/opencode/plugin/lively.js 제거(사용자 플러그인 보존)");
  return 1;
}

// (2) opencode.json 에서 우리 키만 제거. 반환: 제거한 키 수.
export function removeConfigKeys({ dry = false } = {}) {
  const cands = [join(OPENCODE, "opencode.json"), join(OPENCODE, "opencode.jsonc")];
  const path = cands.find((p) => existsSync(p));
  if (!path) { log("  · ~/.config/opencode/opencode.json 없음 — 건너뜀"); return 0; }
  let cfg;
  try { cfg = JSON.parse(readFileSync(path, "utf8")); }
  catch {
    // 주석이 든 .jsonc 등 — 다시 쓰면 사용자 주석·의도가 사라진다. 손대지 않고 수동 안내.
    log(`  ⚠️ ${path.replace(HOME, "~")} 를 JSON 으로 못 읽었습니다 — 수동으로 mcp.lively 와 lively_* permission 을 지우세요.`);
    return 0;
  }
  if (!cfg || typeof cfg !== "object" || Array.isArray(cfg)) { log("  · opencode.json 이 객체가 아님 — 건너뜀"); return 0; }

  let removed = 0;
  if (cfg.mcp && typeof cfg.mcp === "object" && cfg.mcp.lively) { delete cfg.mcp.lively; removed++; }
  if (cfg.mcp && typeof cfg.mcp === "object" && !Object.keys(cfg.mcp).length) delete cfg.mcp;
  // permission — **우리가 심은 키만** 걷는다. 그 목록의 정본은 install 이 남긴 매니페스트다
  //  (멤버가 손으로 넣은 lively_* 가 있어도 그건 매니페스트 밖이라 보존된다).
  let managed = [];
  try { managed = JSON.parse(readFileSync(join(LIVELY, "managed-opencode-permission.json"), "utf8")); if (!Array.isArray(managed)) managed = []; } catch { /* 없으면 permission 은 손대지 않는다 */ }
  if (cfg.permission && typeof cfg.permission === "object" && !Array.isArray(cfg.permission)) {
    for (const k of managed) if (cfg.permission[k] === "allow") { delete cfg.permission[k]; removed++; }
    if (!Object.keys(cfg.permission).length) delete cfg.permission;
  }
  if (!removed) { log("  · opencode.json — lively 키 없음(이미 제거됨/미설치). 무수정"); return 0; }
  if (dry) { log(`  [dry-run] ${path.replace(HOME, "~")} — lively 키 ${removed}건 제거 예정(사용자 키 보존)`); return removed; }
  backup(path, "opencode-config.uninstall.bak");
  try { writeFileSync(path, JSON.stringify(cfg, null, 2) + "\n"); }
  catch (e) { log(`  ⚠️ opencode.json 쓰기 실패: ${e.message}`); return 0; }
  log(`  ✓ ${path.replace(HOME, "~")} — lively 키 ${removed}건 제거(사용자 키 보존, 백업됨)`);
  return removed;
}

// (3) AGENTS.md 의 org-context 센티넬 블록만 제거. 밖은 사용자 지침이므로 보존.
export function stripAgentsBlock(text) {
  const bi = text.indexOf(AG_BEGIN);
  if (bi === -1) return { text, had: false };
  const ei = text.indexOf(AG_END, bi);
  // END 손상 시 BEGIN 한 줄만 떼고 아래 보존(클로버 금지 — codex 어댑터와 같은 규약).
  const after = ei === -1
    ? (text.indexOf("\n", bi) === -1 ? "" : text.slice(text.indexOf("\n", bi) + 1))
    : text.slice(ei + AG_END.length);
  return { text: (text.slice(0, bi) + after).replace(/\n{3,}/g, "\n\n").replace(/^\s+/, ""), had: true };
}

export function removeAgentsContext({ dry = false } = {}) {
  const p = join(OPENCODE, "AGENTS.md");
  if (!existsSync(p)) { log("  · ~/.config/opencode/AGENTS.md 없음 — 건너뜀"); return 0; }
  let cur = "";
  try { cur = readFileSync(p, "utf8"); } catch { return 0; }
  const { text, had } = stripAgentsBlock(cur);
  if (!had) { log("  · ~/.config/opencode/AGENTS.md — lively 블록 없음(사용자 파일) 무수정"); return 0; }
  if (dry) { log("  [dry-run] ~/.config/opencode/AGENTS.md — org-context 블록 제거 예정(사용자 지침 보존)"); return 1; }
  backup(p, "opencode-AGENTS.md.uninstall.bak");
  try {
    if (text.trim()) { writeFileSync(p, text.replace(/\s+$/, "") + "\n"); log("  ✓ ~/.config/opencode/AGENTS.md — org-context 블록 제거(사용자 지침 보존)"); }
    else { rmSync(p, { force: true }); log("  ✓ ~/.config/opencode/AGENTS.md 제거(우리 블록이 전부였음 — 백업됨)"); }
  } catch (e) { log(`  ⚠️ AGENTS.md 정리 실패: ${e.message}`); return 0; }
  return 1;
}

export function uninstallOpencode({ dry = false } = {}) {
  log("  ── OpenCode ──");
  return removePlugin({ dry }) + removeConfigKeys({ dry }) + removeAgentsContext({ dry });
}

// 직접 실행일 때만 수행 — 테스트/오케스트레이터가 export 를 import 해도 제거가 돌지 않게(codex 어댑터와 동일 패턴).
//  realpath 비교: macOS 의 /tmp → /private/tmp 심링크에서도 어긋나지 않는다. 판정 불가면 **실행하지 않는다**
//  (설치기와 반대 방향의 fail-safe — 제거는 의도치 않게 도는 편보다 안 도는 편이 안전하다).
const DIRECT_RUN = (() => {
  try { return realpathSync(fileURLToPath(import.meta.url)) === realpathSync(process.argv[1] || ""); }
  catch { return false; }
})();
if (DIRECT_RUN) uninstallOpencode({ dry: process.argv.includes("--dry-run") });
