#!/usr/bin/env node
// `lively status` 의 **codex 프로브 + 조직 자산 카운트** 계약 (#1475) — 실행: node kit/cli/status-codex-assets.test.mjs
//  실제 ~/.lively·~/.codex 무접촉(LIVELY_HOME 샌드박스 + 닫힌 PATH). 게이트웨이는 로컬 스텁(네트워크 0).
//
// 왜 이 파일이 있나 — 2026-08-04 윈도우 실기기에서 **진단이 전부 초록불인데 아무것도 동작하지 않았다**:
//  ① `codex` 는 config.toml 파싱 실패로 아예 안 떴는데 status 는 "✓ 배선"이라 했다. 판정이 '우리 센티넬 문자열이
//     파일에 있나'뿐이었기 때문이다 — TOML 은 **한 줄의 문법 오류가 파일 전체를 무효화**하므로 그건 '동작한다'가 아니다.
//  ② 서버는 조직 자산 26개를 주는데 그 머신엔 0개였다. 그 사실을 보여주는 표면이 **어디에도 없었다**
//     (자산 sync 는 실패해도 조용하다 — 세션을 막지 않는 게 설계라서). 사용자가 스킬을 못 찾고서야 드러났다.
//  그래서 status 는 (a) codex 에게 **직접 물어** 파싱 가능 여부를 받고 (b) 서버 수 ↔ 로컬 매니페스트 수를 맞댄다.
import { execFile } from "node:child_process";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync, realpathSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { createServer } from "node:http";
import { fileURLToPath } from "node:url";
import { closedPath, writeStubBin } from "../testlib/os-sandbox.mjs";   // 스텁은 윈도우에서도 실행 가능해야 한다(#1510)

const pExecFile = promisify(execFile);
const CLI = join(fileURLToPath(import.meta.url), "..", "lively.mjs");
const BOX = realpathSync(mkdtempSync(join(tmpdir(), "lively-cxstatus-")));

let pass = 0, fail = 0;
const ok = (n) => { pass++; console.log(`ok  ${n}`); };
const bad = (n, why) => { fail++; console.error(`FAIL ${n} — ${why}`); };
const check = (n, cond, why) => (cond ? ok(n) : bad(n, why || "조건 불만족"));

// ── 게이트웨이 스텁 — runtime-config(키트버전) + 자산 목록. 자산 수는 케이스마다 바꾼다. ──
let SERVER_ASSETS = { claude: 26, codex: 25 };
const hits = [];
const srv = createServer((req, res) => {
  hits.push(req.url.split("?")[0]);
  const send = (o) => { res.writeHead(200, { "content-type": "application/json" }); res.end(JSON.stringify(o)); };
  if (req.url.startsWith("/api/ui/org/runtime-config")) return send({ kit_version: "test", hooks: {} });
  if (req.url.startsWith("/api/ui/org/runner/assets")) {
    const h = new URL(req.url, "http://x").searchParams.get("harness") || "claude";
    return send({ assets: Array.from({ length: SERVER_ASSETS[h] ?? 0 }, (_, i) => ({ id: `a${i}`, kind: "skill" })) });
  }
  if (req.url.startsWith("/api/ui/me/profile")) return send({ id: "tester", display_name: "테스터" });
  send({});
});
await new Promise((r) => srv.listen(0, "127.0.0.1", r));
const GW = `http://127.0.0.1:${srv.address().port}`;

// ── codex 스텁 — 실물 `codex mcp get lively` 출력 형식. 호출 argv 는 로그에 남긴다(배선 단언용). ──
const CX = {
  ok: { out: ["lively", "  enabled: true", "  transport: stdio"], code: 0 },
  // 오늘 사고 그대로 — config 가 통째로 무효라 codex 는 아무것도 못 한다.
  brokenConfig: { err: ["Error loading config.toml:", "C:\\\\Users\\\\x\\\\.codex\\\\config.toml:14:24: too few unicode value digits"], code: 1 },
  absent: { err: ["Error: No MCP server named 'lively' found."], code: 1 },
  oldVersion: { err: ["error: unknown command 'get'"], code: 1 },   // 판정 불가 → 단정하지 않아야 한다
};

function mkCase(name, { codexMode = "ok", codexInstalled = true, localAssets = { claude: 26, codex: 25 } } = {}) {
  const home = join(BOX, name);
  const bin = join(home, "stub-bin");
  mkdirSync(bin, { recursive: true });
  mkdirSync(join(home, ".lively"), { recursive: true });
  const log = join(home, "codex-argv.log");
  writeFileSync(join(home, ".lively", "gateway-url"), GW + "\n");
  writeFileSync(join(home, ".lively", "token"), "t\n");
  // 로컬 매니페스트 = '라이블리가 심은 것'의 기록. 이게 서버 수와 어긋나면 그 머신에서 materialize 가 안 된 것이다.
  const manifest = {};
  for (const [h, n] of Object.entries(localAssets)) manifest[h] = Object.fromEntries(Array.from({ length: n }, (_, i) => [`a${i}`, { kind: "skill" }]));
  writeFileSync(join(home, ".lively", "managed-harness-assets.json"), JSON.stringify(manifest));
  // codex 가 배선된 것처럼 보이게(센티넬 문자열) — '배선됨'과 '동작함'이 다르다는 게 이 테스트의 요지다.
  mkdirSync(join(home, ".codex"), { recursive: true });
  writeFileSync(join(home, ".codex", "config.toml"), "# >>> lively-managed (auto-generated by workflow-std/adapters/codex — do not edit) >>>\n[mcp_servers.lively]\n# <<< lively-managed <<<\n");
  if (codexInstalled) {
    // 스텁 본문은 JS 한 벌 — sh 로 쓰면 윈도우에서 실행조차 안 돼 가로채기가 조용히 실패한다(#1510).
    const g = CX[codexMode];
    writeStubBin(bin, "codex", [
      'import { appendFileSync } from "node:fs";',
      "const a = process.argv.slice(2);",
      `appendFileSync(${JSON.stringify(log)}, a.join(" ") + "\\n");`,
      'if (a[0] === "mcp" && a[1] === "get") {',
      ...(g.out || []).map((l) => `  console.log(${JSON.stringify(l)});`),
      ...(g.err || []).map((l) => `  console.error(${JSON.stringify(l)});`),
      `  process.exit(${g.code});`,
      "}",
      "process.exit(0);",
    ].join("\n"));
  }
  return { home, bin, log, calls: () => (existsSync(log) ? readFileSync(log, "utf8").trim().split("\n").filter(Boolean) : []) };
}

async function statusOf(c) {
  const env = {
    ...process.env,
    PATH: closedPath(c.bin),                          // 닫힌 PATH — 실제 codex/claude 가 안 잡히게
    LIVELY_HOME: c.home,
    CLAUDE_CONFIG_DIR: join(c.home, "claude-cfg"),
    LIVELY_GATEWAY_URL: "", LIVELY_TOKEN: "",         // 파일(샌드박스)에서 읽게 — env 가 이기면 실 게이트웨이로 샌다
    NO_COLOR: "1",
  };
  const r = await pExecFile(process.execPath, [CLI, "status", "--json"], { cwd: c.home, env, timeout: 30_000 })
    .catch((e) => ({ stdout: e.stdout ?? "", stderr: e.stderr ?? String(e.message) }));
  try { return JSON.parse(r.stdout).harness; }
  catch { throw new Error(`status --json 파싱 실패: ${String(r.stdout).slice(0, 200)} / ${String(r.stderr).slice(-300)}`); }
}

try {
  // ── C1 정상 — 파싱 OK · 등록됨 · transport 까지 보고 ────────────────────────
  {
    const c = mkCase("ok");
    const h = await statusOf(c);
    check("C1 codex 정상 → configOk·mcp·transport 보고",
      h.codex.configOk === true && h.codex.mcp === true && h.codex.transport === "stdio", JSON.stringify(h.codex));
    check("C1b 배선 — codex 스텁이 실제로 불렸다(관측 장치 생존)", c.calls().some((l) => /^mcp get lively/.test(l)), JSON.stringify(c.calls()));
  }

  // ── C2 config 파손 — **오늘 사고**. '배선됨'은 여전히 true 지만 동작은 false 여야 한다 ──
  {
    const h = await statusOf(mkCase("broken", { codexMode: "brokenConfig" }));
    check("C2 config 파손 → configOk=false (센티넬은 있으니 wired 는 true 인 채로)",
      h.codex.configOk === false && h.codex.wired === true, JSON.stringify(h.codex));
    // ⚠ 단언은 `!== true` 다(`=== false` 가 아니라). config 가 깨지면 `codex mcp get` 이 아무것도 못 알려주므로
    //  등록 여부는 **판정 불가(null)** 가 정확한 사실이고, false(미등록)로 단정하면 "lively update" 같은 헛다리
    //  조치를 부른다(#1505 실측: 코덱스 세션 안에서 doctor 가 계속 '미등록'을 냈다). 이 케이스의 계약은
    //  "참으로 말하지 않는다" 이지 "거짓으로 말한다" 가 아니다 — null·false 둘 다 통과해야 한다.
    check("C2b config 파손이면 MCP 등록을 참으로 말하지 않는다", h.codex.mcp !== true, JSON.stringify(h.codex));
  }

  // ── C3 파일은 읽히는데 우리 서버만 없음 ────────────────────────────────────
  {
    const h = await statusOf(mkCase("absent", { codexMode: "absent" }));
    check("C3 서버 미등록 → configOk=true · mcp=false", h.codex.configOk === true && h.codex.mcp === false, JSON.stringify(h.codex));
  }

  // ── C4 판정 불가(구버전 등) — **모르는 걸 아는 척하지 않는다** ─────────────
  {
    const h = await statusOf(mkCase("old", { codexMode: "oldVersion" }));
    check("C4 출력 미상 → configOk=null(단정 안 함)", h.codex.configOk === null, JSON.stringify(h.codex));
  }

  // ── C5 codex 미설치 — 프로브 자체를 안 한다 ────────────────────────────────
  {
    const c = mkCase("nocodex", { codexInstalled: false });
    const h = await statusOf(c);
    check("C5 미설치 → installed=false · 프로브 호출 0건", h.codex.installed === false && c.calls().length === 0, JSON.stringify([h.codex, c.calls()]));
  }

  // ── C6 자산 일치 — 서버 수 == 로컬 수 ──────────────────────────────────────
  {
    SERVER_ASSETS = { claude: 26, codex: 25 };
    const h = await statusOf(mkCase("assets-ok", { localAssets: { claude: 26, codex: 25 } }));
    check("C6 자산 일치 → codex 25/25 보고", h.codex.assets && h.codex.assets.local === 25 && h.codex.assets.server === 25, JSON.stringify(h.codex.assets));
  }

  // ── C7 자산 0 — **윈도우에서 실제로 일어난 상태**. 이게 안 보이면 신고 전엔 아무도 모른다 ──
  //  ⚠ 설치된 하네스만 조회한다(안 깔린 하네스에 자산을 묻는 건 의미가 없다) → 이 케이스는 codex 축으로 본다.
  {
    SERVER_ASSETS = { claude: 26, codex: 25 };
    const h = await statusOf(mkCase("assets-zero", { localAssets: { claude: 0, codex: 0 } }));
    check("C7 자산 0 → 로컬 0 · 서버 25 로 드러난다",
      h.codex.assets && h.codex.assets.local === 0 && h.codex.assets.server === 25, JSON.stringify(h.codex.assets));
    check("C7b 배선 — 자산 엔드포인트를 실제로 물었다", hits.some((u) => u === "/api/ui/org/runner/assets"), JSON.stringify([...new Set(hits)]));
  }

  // ── C8 매니페스트 자체가 없음(설치 직후) — 0 으로 보고하고 죽지 않는다 ─────
  {
    const c = mkCase("nomanifest");
    rmSync(join(c.home, ".lively", "managed-harness-assets.json"), { force: true });
    const h = await statusOf(c);
    check("C8 매니페스트 부재 → 0/N 으로 보고(예외 없음)", h.codex.assets && h.codex.assets.local === 0, JSON.stringify(h.codex.assets));
  }

  console.log(`\n${fail ? "FAIL" : "PASS"} — ${pass} passed, ${fail} failed`);
} finally {
  srv.close();
  rmSync(BOX, { recursive: true, force: true });
}
process.exit(fail ? 1 : 0);
