#!/usr/bin/env node
// Codex 하네스 어댑터 — user-level 설치(D5 멀티하네스). 어느 폴더에서 codex 를 켜든 컨텍스트+리플렉스가 오게 한다.
// Claude 어댑터(adapters/claude/install.mjs)의 형제 — 같은 ~/.lively 자산을 공유하고, Codex 전용 표면만 발행한다.
//
// 하는 일(전부 idempotent):
//  (a) ~/.lively/context.md  ← 정적 org-context (buildStaticContext, 토큰/시크릿 없음) [claude 와 공유]
//  (b) ~/.lively/hooks/{session-preload,work-flag,stop-writeback-gate}.mjs ← 훅 스크립트 복사(chmod 755) [공유]
//  (c) ~/.codex/AGENTS.md  ← 정적 org-context (Codex 가 글로벌 인스트럭션으로 네이티브 로드 — 훅 trust 무관 항상 적용)
//  (d) ~/.codex/config.toml ← SAFE-MERGE(백업 먼저): lively-managed 센티넬 블록만 surgical replace —
//        [[hooks.SessionStart|PostToolUse|Stop]] (공유 훅 절대경로, node, LIVELY_HARNESS=codex)
//        + [mcp_servers.lively] (Streamable HTTP url + bearer_token_env_var — 토큰 리터럴 절대 미기입).
//        사용자 기존 키(model/auth-project trust/tui/다른 mcp_servers/다른 hooks)는 한 바이트도 안 건드린다.
//  (e) ~/.lively/work-roots ← 자가 게이팅용 work-root 시드(없을 때만, 기존 보존) [공유]
//
// 사용법: node adapters/codex/install.mjs --org <org-content-dir> [--org-name <name>] [--work-root <abs>]…
//        [--gateway-url <url>]  (미지정 시 ~/.lively/gateway-url, 그것도 없으면 http://localhost:8080)
//   user-install.mjs 가 토큰/게이트웨이 기록 후 이걸 호출한다(claude 어댑터와 병렬 — 둘 다 설치되면 둘 다).
//
// Codex 0.138.0 계약(임베드 스키마 + developers.openai.com/codex 확인):
//  - 훅 기본 활성([features] hooks = stable/true). 별도 enable 불요.
//  - config.toml [hooks] 이벤트 테이블명 = PascalCase(SessionStart/PostToolUse/Stop …) — hook_event_name const 와 동일.
//    핸들러 = [[hooks.<E>.hooks]] { type="command", command, timeout }. Stop 은 matcher 미지원.
//    ※ 0.138 은 위 3개 외에 **UserPromptSubmit·PreToolUse·PreCompact/PostCompact·PermissionRequest·SubagentStart** 도 지원
//      (바이너리 임베드 스키마 `*HookSpecificOutputWire` 실측 확인). 우리는 현재 3개만 와이어 — per-prompt 도메인 메모리
//      recall 같은 기능엔 `UserPromptSubmit`(stdout/additionalContext 주입) 추가 필요. "3개뿐"으로 오해 금지(하네스 패리티).
//  - SessionStart 출력 = JSON 봉투(hookSpecificOutput.additionalContext) — 공유 훅이 LIVELY_HARNESS=codex 로 분기.
//  - Stop 출력 = {"decision":"block","reason":…} (Claude 와 동일). stop_hook_active 루프가드 동일.
//  - 비관리(command) 훅은 최초 1회 trust 필요(해시 기반). 대화형은 codex /hooks 로 신뢰,
//    헤드리스(codex exec)는 --dangerously-bypass-hook-trust. trusted_hash 는 어댑터가 굽지 않는다(계산 불가/취약).
//  - MCP: [mcp_servers.lively] url(Streamable HTTP) + bearer_token_env_var="LIVELY_TOKEN". 토큰은 env 로만.

import {
  readFileSync,
  writeFileSync,
  appendFileSync,
  existsSync,
  mkdirSync,
  copyFileSync,
  chmodSync,
} from "node:fs";
import { homedir } from "node:os";
import { join, dirname, resolve, basename } from "node:path";
import { fileURLToPath } from "node:url";
import { buildStaticContext, deriveOrgName } from "../../generator/build-context.mjs";
import { WORK_ROOTS_HEADER } from "../../setup/work-roots-header.mjs";

// P-V3-5 Part A: 정적 폴백 context.md/AGENTS.md 단일소스 — 게이트웨이 가용 시 DB-materialize 한 정적 컨텍스트(=preview,
//  DB Knowledge Index)를 받고, 다운/오프라인이면 파일기반 buildStaticContext 로 폴백(진실원천 이원화 해소). claude 어댑터와 동형.
async function fetchDbStaticContext(home) {
  const readLively = (rel) => { try { return readFileSync(join(home, ".lively", rel), "utf8").trim() || null; } catch { return null; } };
  const token = (process.env.LIVELY_TOKEN || "").trim() || readLively("token");
  if (!token) return null;
  const gw = ((process.env.LIVELY_GATEWAY_URL || "").trim() || readLively("gateway-url") || "http://localhost:8080").replace(/\/$/, "");
  const ctl = new AbortController();
  const timer = setTimeout(() => ctl.abort(), 4000);
  try {
    const res = await fetch(`${gw}/api/ui/org/preview`, { signal: ctl.signal, headers: { authorization: `Bearer ${token}` } });
    if (!res.ok) return null;
    const j = await res.json();
    const ctx = j && typeof j.context === "string" ? j.context.trim() : "";
    return ctx ? ctx + "\n" : null;
  } catch { return null; }
  finally { clearTimeout(timer); }
}

const KIT_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const kitAbs = (p) => join(KIT_ROOT, p);
// HOME: 기본 OS homedir(), env LIVELY_HOME 로 리다이렉트 가능(샌드박스 격리 — uninstall 과 동일 계약).
//  ※ install/uninstall 대칭: 라운드트립 테스트 시 양쪽에 같은 LIVELY_HOME 을 지정해야 한쪽만 라이브에 닿는 footgun 을 막는다.
const HOME = process.env.LIVELY_HOME || homedir();
const LIVELY = join(HOME, ".lively");
const CODEX = join(HOME, ".codex");
const HOOK_SCRIPTS = ["session-preload.mjs", "work-flag.mjs", "stop-writeback-gate.mjs"];
// AGENTS.md 센티넬(setup/user-install.mjs·user-uninstall.mjs 와 **정확히 동일 리터럴** — 센티넬 일치 필수).
//  org-context 를 관리 블록으로 비파괴 머지(사용자 기존 글로벌 지침/메모리 보존). config.toml 센티넬과 동형.
const AG_BEGIN = "<!-- >>> lively-managed org-context (auto-generated by workflow-std — do not edit) >>> -->";
const AG_END = "<!-- <<< lively-managed <<< -->";
function agentsMerge(existing, ctx) {
  let user = existing;
  const bi = existing.indexOf(AG_BEGIN);
  if (bi !== -1) {
    const ei = existing.indexOf(AG_END, bi);
    user = existing.slice(0, bi) + (ei === -1 ? "" : existing.slice(ei + AG_END.length));
  }
  user = user.replace(/\n{3,}/g, "\n\n").replace(/\s+$/, "");
  const block = AG_BEGIN + "\n" + ctx.replace(/\s+$/, "") + "\n" + AG_END + "\n";
  return (user ? user + "\n\n" : "") + block;
}

// lively-managed 센티넬 — config.toml 안에서 우리가 소유하는 영역을 정확히 구분.
//  이 두 줄 사이만 surgical replace(재실행 idempotent). 바깥은 사용자 영역 — 절대 불가침.
const BEGIN = "# >>> lively-managed (auto-generated by workflow-std/adapters/codex — do not edit) >>>";
const END = "# <<< lively-managed <<<";
// R3 리네임 마이그레이션 호환: 이전 제품명(harness-kit) 으로 깐 관리 블록도 인식한다.
//  센티넬 매칭이 BEGIN 리터럴 정확일치였으므로, 리네임 직후 첫 재설치가 옛 블록을 못 찾아
//  새 블록을 *append* → [mcp_servers.lively]/[hooks] 중복(TOML 무효) 위험이 있었다.
//  옛 BEGIN 도 관리영역으로 보고 surgical replace 한다(END 는 옛·새 동일). 1주기 마이그레이션 가드.
const LEGACY_BEGINS = [
  "# >>> lively-managed (auto-generated by lively-harness-kit/adapters/codex — do not edit) >>>",
];

// user-level 훅 command — Windows: `env` 프리픽스 불가 → 하네스 argv + forward-slash 절대경로.
//  Mac/Linux: 기존 env 형 유지(idempotency 키 안정). 둘 다 출력 봉투 분기는 session-preload 가 argv/env 로 인식.
// #355: 번들 node(~/.lively/runtime/current/bin/node — 안정 심링크)가 있으면 그 절대경로로 실행해 실행 셸 PATH 무관.
//  없으면(시스템 node) 기존대로 `node`(PATH 탐색). Windows 는 User PATH 로 처리 — bare 유지.
const bundledNode = join(LIVELY, "runtime", "current", "bin", "node");
const NODEBIN = (process.platform !== "win32" && existsSync(bundledNode)) ? bundledNode : "node";
const hookCmd = (script) => process.platform === "win32"
  ? `node "${join(LIVELY, "hooks", script).replace(/\\/g, "/")}" --harness codex`
  : `env LIVELY_HARNESS=codex "${NODEBIN}" "${join(LIVELY, "hooks", script)}"`;

// lively-managed config.toml 블록 본문 생성(센티넬 사이에 들어갈 내용).
//  gatewayUrl 은 /mcp 가 붙은 Streamable HTTP 엔드포인트. 토큰 리터럴 없음.
function managedBlock(mcpUrl) {
  const L = [];
  L.push(BEGIN);
  L.push("");
  // ── MCP: lively 게이트웨이 (Streamable HTTP) ──
  L.push("[mcp_servers.lively]");
  L.push(`url = "${mcpUrl}"`);
  L.push('bearer_token_env_var = "LIVELY_TOKEN"');
  L.push("");
  // 작업자(AI) 식별 — 게이트웨이가 이 헤더로 어떤 하네스인지 안다(프로젝트 #182). codex 는 User-Agent 를 안 보내므로
  //  per-harness 설치가 명시 stamp 해야 게이트웨이가 author_agent 를 자기보고 없이 권위 있게 채운다.
  L.push("[mcp_servers.lively.http_headers]");
  L.push('x-lively-harness = "codex"');
  L.push("");
  // ── 훅: SessionStart(컨텍스트 주입) / PostToolUse(작업 플래그) / Stop(라이트백 게이트) ──
  L.push("[[hooks.SessionStart]]");
  L.push('matcher = "startup|resume|clear"');
  L.push("[[hooks.SessionStart.hooks]]");
  L.push('type = "command"');
  L.push(`command = '${hookCmd("session-preload.mjs")}'`);
  L.push("timeout = 10");
  L.push("");
  L.push("[[hooks.PostToolUse]]");
  L.push('matcher = "mcp__lively__.*"');
  L.push("[[hooks.PostToolUse.hooks]]");
  L.push('type = "command"');
  L.push(`command = '${hookCmd("work-flag.mjs")}'`);
  L.push("timeout = 5");
  L.push("");
  L.push("[[hooks.PostToolUse]]");
  L.push('matcher = "Edit|Write|MultiEdit|NotebookEdit|apply_patch"');
  L.push("[[hooks.PostToolUse.hooks]]");
  L.push('type = "command"');
  L.push(`command = '${hookCmd("work-flag.mjs")}'`);
  L.push("timeout = 5");
  L.push("");
  L.push("[[hooks.Stop]]"); // Stop 은 matcher 미지원
  L.push("[[hooks.Stop.hooks]]");
  L.push('type = "command"');
  L.push(`command = '${hookCmd("stop-writeback-gate.mjs")}'`);
  L.push("timeout = 10");
  L.push("");
  L.push(END);
  return L.join("\n");
}

// 센티넬 영역을 제외한 '사용자 본문' 추출(idempotency 의 핵심).
//  BEGIN..END 한 쌍을 통째 제거하고 나머지를 돌려준다(앞뒤 공백 트림).
function stripManaged(text) {
  // 현재 BEGIN 우선, 없으면 옛(harness-kit) BEGIN 도 관리영역으로 인식(R3 리네임 마이그레이션).
  let bi = text.indexOf(BEGIN);
  let beginLen = BEGIN.length;
  if (bi === -1) {
    for (const lb of LEGACY_BEGINS) {
      const li = text.indexOf(lb);
      if (li !== -1) { bi = li; beginLen = lb.length; break; }
    }
  }
  if (bi === -1) return { user: text, hadManaged: false };
  const ei = text.indexOf(END, bi);
  if (ei === -1) {
    // END 가 없으면(손상/수동편집) — BEGIN 한 줄'만' 관리영역으로 보고 제거하고, BEGIN 아래 사용자 키는 보존한다.
    //  (예전엔 BEGIN 이후 전부를 잘라내 아래 사용자 테이블이 소실됐다. 어댑터는 항상 BEGIN/END 쌍을 쓰므로
    //   정상 동작에선 이 경로에 안 오지만, 손상된 마커 아래 사용자 키 침묵 소실을 막는다 — 클로버 금지.)
    const beforeOrphan = text.slice(0, bi);
    const eol = text.indexOf("\n", bi);
    const afterOrphan = eol === -1 ? "" : text.slice(eol + 1); // BEGIN 줄만 떼고 그 아래는 전부 보존
    return { user: (beforeOrphan + afterOrphan).replace(/\n{3,}/g, "\n\n").trim() + "\n", hadManaged: true };
  }
  const before = text.slice(0, bi);
  const after = text.slice(ei + END.length);
  return { user: (before + after).replace(/\n{3,}/g, "\n\n").trim() + "\n", hadManaged: true };
}

// 사용자 본문(센티넬 영역 밖)에 우리 테이블 헤더와 충돌하는 정의가 있는지 검사.
//  있으면 중복 정의 = TOML 무효이므로 그 부분 머지를 거부하고 경고(클로버 금지 > 기능).
function detectConflicts(userBody) {
  const conflicts = [];
  if (/^\s*\[mcp_servers\.lively\]\s*$/m.test(userBody)) conflicts.push("[mcp_servers.lively]");
  if (/^\s*\[\[hooks\.(SessionStart|PostToolUse|Stop)(\.hooks)?\]\]\s*$/m.test(userBody)) {
    conflicts.push("[[hooks.SessionStart|PostToolUse|Stop]]");
  }
  return conflicts;
}

// LIVELY_TOKEN 을 codex 프로세스 환경에 전달(MCP bearer 인증의 전제).
//  Codex 는 config.toml 의 토큰 리터럴을 거부(bearer_token_env_var 만 허용)하므로, 토큰은 셸 환경에 있어야 한다.
//  Claude 와의 비대칭(claude 는 ~/.claude.json 헤더에 토큰 인라인 → 연결됨; codex 는 리터럴 거부 → env 필요)을 메운다.
//  가드레일 준수: 토큰 리터럴을 어떤 파일에도 굽지 않는다 — rc 에는 `$(cat ~/.lively/token)` 런타임 읽기만 export.
//  센티넬 가드로 idempotent(재실행해도 중복 추가 없음).
//  ⚠ 이 export 는 **무조건 덮어쓴다**(조건은 파일 존재뿐) — 즉 새 셸의 LIVELY_TOKEN 은 곧
//   '셸 시작 시각의 ~/.lively/token 스냅샷'이고, override 가 아니라 **파일의 캐시**다.
//   CLI 는 이 사실에 맞춰 파일을 정본으로 읽는다(#916 — kit/cli/lively.mjs 의 token() 주석 참조).
//   env 를 신원의 정본으로 취급하는 코드를 새로 만들지 말 것: 로그인 직후 같은 셸에서 반드시 스테일이다.
//  ⛔ **`[ -z "${LIVELY_TOKEN:-}" ]` 같은 '이미 있으면 두기' 가드를 넣지 말 것.** 무조건 덮어쓰기가
//   스테일 env 의 **유일한 자가치유 경로**다(새 셸이면 낫는다). 가드를 넣으면 옛 토큰이 모든 새 셸에
//   영구 고착돼 #916 이 회복 불가능해진다. 이미 한 번 겪은 사고다 — deploy/provision-member.sh:86
//   ("과거 `-z LIVELY_TOKEN` 가드는 옛 셸에 남은 stale 토큰이 파일 토큰을 shadow 해 401 을 유발했다").
const RC_BEGIN = "# >>> lively-managed (codex LIVELY_TOKEN) >>>";
const RC_END = "# <<< lively-managed (codex LIVELY_TOKEN) <<<";
function wireCodexTokenEnv() {
  // 토큰 파일이 아직 없으면(셋업 순서상 드묾) export 블록은 그래도 심는다 — 파일 생기면 다음 셸부터 동작.
  const block = [
    RC_BEGIN,
    "# codex 의 lively MCP 가 bearer_token_env_var=LIVELY_TOKEN 으로 인증하려면 셸에 토큰이 있어야 함.",
    "# 토큰 리터럴은 적지 않는다 — 런타임에 ~/.lively/token 을 읽는다(없으면 빈 값, 훅은 fail-open).",
    'if [ -r "$HOME/.lively/token" ]; then export LIVELY_TOKEN="$(cat "$HOME/.lively/token")"; fi',
    RC_END,
  ].join("\n");

  // zsh(macOS 기본) + bash 양쪽 커버. 존재하는 rc 에 머지하고, 둘 다 없으면 zsh 기본(.zshrc)을 만든다.
  const candidates = [".zshrc", ".bashrc", ".bash_profile", ".profile"].map((f) => join(HOME, f));
  let targets = candidates.filter((p) => existsSync(p));
  if (!targets.length) targets = [join(HOME, ".zshrc")];

  let wired = 0;
  for (const rc of targets) {
    let cur = "";
    try { cur = existsSync(rc) ? readFileSync(rc, "utf8") : ""; } catch { continue; }
    const bi = cur.indexOf(RC_BEGIN);
    let next;
    if (bi !== -1) {
      const ei = cur.indexOf(RC_END, bi);
      if (ei === -1) { // 손상 — BEGIN 줄만 떼고 재삽입(아래 사용자 내용 보존)
        const eol = cur.indexOf("\n", bi);
        const before = cur.slice(0, bi);
        const after = eol === -1 ? "" : cur.slice(eol + 1);
        next = before.replace(/\s+$/, "") + "\n" + (after.trim() ? after.replace(/^\s+/, "") : "");
        next = next.replace(/\s+$/, "") + "\n\n" + block + "\n";
      } else { // 정상 — 블록 surgical 교체(내용 동일하면 무변경)
        const before = cur.slice(0, bi);
        const afterRaw = cur.slice(ei + RC_END.length);
        const merged = (before + afterRaw).replace(/\n{3,}/g, "\n\n");
        next = merged.replace(/\s+$/, "") + "\n\n" + block + "\n";
        if (next === cur) { console.log(`  · ${rc.replace(HOME, "~")} (LIVELY_TOKEN export 기존 유지)`); continue; }
      }
    } else {
      next = (cur.replace(/\s+$/, "") + (cur.trim() ? "\n\n" : "")) + block + "\n";
    }
    try {
      writeFileSync(rc, next);
      wired++;
      console.log(`  ✓ ${rc.replace(HOME, "~")} (LIVELY_TOKEN export 추가 — 토큰 리터럴 없음 · 새 셸부터 적용)`);
    } catch (e) {
      console.warn(`  ⚠️ ${rc.replace(HOME, "~")} 쓰기 실패(${e.message}) — 수동으로 LIVELY_TOKEN export 필요.`);
    }
  }
  if (wired) {
    console.log("    (현재 열린 셸에는 즉시 반영 안 됨 — 새 터미널을 열거나 `source ~/.zshrc` 후 codex 실행)");
  }
}

function safeMergeCodexConfig(mcpUrl) {
  const cfgPath = join(CODEX, "config.toml");
  mkdirSync(CODEX, { recursive: true });

  let raw = "";
  if (existsSync(cfgPath)) {
    // 백업 먼저(클로버 금지). 최초 1회 원본 보존 + 매 실행 직전본 보존.
    const backupDir = join(LIVELY, "backups");
    mkdirSync(backupDir, { recursive: true });
    try {
      const origPath = join(backupDir, "config.toml.codex.orig");
      if (!existsSync(origPath)) copyFileSync(cfgPath, origPath); // 진짜 최초 원본은 1회만
      copyFileSync(cfgPath, join(backupDir, "config.toml.codex.bak")); // 직전본
    } catch (e) {
      console.error(`✗ ~/.codex/config.toml 백업 실패 — 중단(클로버 금지): ${e.message}`);
      process.exit(1);
    }
    raw = readFileSync(cfgPath, "utf8");
  }

  const { user, hadManaged } = stripManaged(raw);
  const conflicts = detectConflicts(user);
  if (conflicts.length) {
    console.warn(
      `  ⚠️ ~/.codex/config.toml 사용자 영역에 충돌 테이블(${conflicts.join(", ")}) 존재 — ` +
        "중복 정의는 TOML 무효라 머지 건너뜀(기존 파일 무수정). 수동 정리 후 재실행하세요.",
    );
    return false;
  }

  const userTrimmed = user.replace(/\s+$/, "");
  const next =
    (userTrimmed ? userTrimmed + "\n\n" : "") + managedBlock(mcpUrl) + "\n";
  writeFileSync(cfgPath, next);
  chmodSync(cfgPath, 0o600);
  console.log(
    `  ✓ ~/.codex/config.toml (lively-managed 블록 ${hadManaged ? "교체" : "추가"} · 사용자 키 보존 · 토큰 리터럴 없음)`,
  );
  return true;
}

// work-roots 시드 — claude 어댑터와 동일 동작(없을 때만 생성/추가, 기존 보존).
function seedWorkRoots(roots) {
  if (!roots.length) return;
  const path = join(LIVELY, "work-roots");
  let existing = [];
  if (existsSync(path)) {
    existing = readFileSync(path, "utf8").split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
  }
  const set = new Set(existing.filter((l) => !l.startsWith("#")));
  let added = 0;
  for (const r of roots) {
    const abs = resolve(r);
    if (!set.has(abs)) { existing.push(abs); set.add(abs); added++; }
  }
  if (added || !existsSync(path)) {
    const header = WORK_ROOTS_HEADER;
    const body = [header, ...existing.filter((l) => l.trim() && !l.startsWith("#"))].join("\n") + "\n";
    writeFileSync(path, body);
    chmodSync(path, 0o600);
    console.log(`  ✓ ~/.lively/work-roots (시드 ${added}건 추가)`);
  } else {
    console.log("  · ~/.lively/work-roots (기존 유지)");
  }
}

async function main() {
  const args = process.argv.slice(2);
  const getOpt = (name) => { const i = args.indexOf(name); return i !== -1 ? args[i + 1] : null; };
  const orgArg = getOpt("--org");
  if (!orgArg) {
    console.error("✗ --org <org-content-dir> 가 필요합니다.");
    process.exit(1);
  }
  const orgRoot = resolve(process.cwd(), orgArg);
  const orgNameArg = getOpt("--org-name");
  const workRoots = [];
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--work-root" && args[i + 1]) workRoots.push(args[i + 1]);
  }

  // 게이트웨이 URL 도출: --gateway-url > ~/.lively/gateway-url > 기본. /mcp 엔드포인트로 정규화.
  const readLively = (rel) => {
    try { return readFileSync(join(LIVELY, rel), "utf8").trim() || null; } catch { return null; }
  };
  const gwBase = (getOpt("--gateway-url") || readLively("gateway-url") || "http://localhost:8080").replace(/\/+$/, "");
  const mcpUrl = /\/mcp$/.test(gwBase) ? gwBase : gwBase + "/mcp";

  console.log(`▶ Codex 어댑터 user-level 설치 (org=${basename(orgRoot)})`);
  mkdirSync(LIVELY, { recursive: true, mode: 0o700 });

  // (a) 정적 org-context + org 표시명 사이드카(claude 어댑터와 동일 자산 — 공유).
  //  단일소스 우선순위: 게이트웨이 DB-materialize(preview, DB Knowledge Index) > 파일기반 buildStaticContext(오프라인 폴백).
  //  org 표시명은 항상 파일기반에서 도출(중립·org-agnostic). ctx 는 context.md 와 ~/.codex/AGENTS.md 양쪽에 쓰인다.
  const orgName = orgNameArg && String(orgNameArg).trim() ? String(orgNameArg).trim() : deriveOrgName(orgRoot);
  const dbCtx = await fetchDbStaticContext(HOME);
  const ctx = dbCtx ?? buildStaticContext(orgRoot, orgName).context;
  const ctxSource = dbCtx ? "게이트웨이 DB(Knowledge Index)" : "파일기반 폴백(오프라인)";
  writeFileSync(join(LIVELY, "context.md"), ctx);
  chmodSync(join(LIVELY, "context.md"), 0o600);
  writeFileSync(join(LIVELY, "org-name"), orgName + "\n");
  chmodSync(join(LIVELY, "org-name"), 0o600);
  console.log(`  ✓ ~/.lively/context.md (${(Buffer.byteLength(ctx, "utf8") / 1024).toFixed(1)} KiB · ${ctxSource}) · org-name=${orgName}`);

  // (b) 훅 스크립트 복사(공유).
  const hooksDir = join(LIVELY, "hooks");
  mkdirSync(hooksDir, { recursive: true });
  for (const f of HOOK_SCRIPTS) {
    copyFileSync(kitAbs(join("hooks", f)), join(hooksDir, f));
    chmodSync(join(hooksDir, f), 0o755);
  }
  console.log(`  ✓ ~/.lively/hooks/ (${HOOK_SCRIPTS.length}개)`);

  // (c) ~/.codex/AGENTS.md — 정적 org-context(Codex 글로벌 인스트럭션, 훅 trust 무관 항상 로드).
  //  Codex 32KiB 글로벌 인스트럭션 권장 한도 — 초과 시 경고만(차단 안 함).
  mkdirSync(CODEX, { recursive: true });
  const agentsPath = join(CODEX, "AGENTS.md");
  // 비파괴 머지(사용자 기존 글로벌 지침/메모리 보존) + 백업 — config.toml 보호 패턴 미러.
  let existingAgents = "";
  if (existsSync(agentsPath)) {
    try { existingAgents = readFileSync(agentsPath, "utf8"); } catch { existingAgents = ""; }
    const backupDir = join(LIVELY, "backups"); mkdirSync(backupDir, { recursive: true });
    try {
      const orig = join(backupDir, "codex-AGENTS.md.orig");
      if (!existsSync(orig)) copyFileSync(agentsPath, orig);
      copyFileSync(agentsPath, join(backupDir, "codex-AGENTS.md.bak"));
    } catch { /* 백업 실패해도 머지는 비파괴라 진행 */ }
  }
  writeFileSync(agentsPath, agentsMerge(existingAgents, ctx));
  const bytes = Buffer.byteLength(ctx, "utf8");
  console.log(
    `  ✓ ~/.codex/AGENTS.md (${(bytes / 1024).toFixed(1)} KiB)${bytes > 32 * 1024 ? "  ⚠️ 32KiB 초과 — 분량 검토" : ""}`,
  );

  // (d) config.toml 안전 머지([hooks] + [mcp_servers.lively], 센티넬 surgical).
  safeMergeCodexConfig(mcpUrl);

  // (d2) LIVELY_TOKEN 셸 env 전달 — config.toml 의 bearer_token_env_var 가 가리키는 그 env var.
  //  이게 없으면 새 셸에서 codex 의 lively MCP 가 401(인증 실패). 토큰 리터럴은 안 굽는다(rc 에 런타임 읽기만).
  wireCodexTokenEnv();

  // (e) work-root 시드(공유).
  seedWorkRoots(workRoots);

  console.log("✓ Codex 어댑터 설치 완료.");
  console.log("  · MCP 확인:  codex mcp list  (lively 가 보여야 함 — 새 셸에서 LIVELY_TOKEN 인증)");
  console.log("  · 훅 trust:  대화형은 codex 에서 /hooks 로 신뢰 / 헤드리스는 codex exec --dangerously-bypass-hook-trust");
  console.log("  · 헤드리스 한계: codex exec 는 라이프사이클 훅 미발화(0.138.0) — AGENTS.md 정적 컨텍스트만. 라이브 현황/Stop 게이트는 대화형 TUI 에서.");
  console.log("  · incognito: 환경변수 LIVELY_OFF=1 (훅 라이브 현황 침묵 — AGENTS.md 정적 컨텍스트는 유지)");
}

main().catch((e) => { console.error(`✗ 설치 실패: ${e?.message || e}`); process.exit(1); });
