#!/usr/bin/env node
// Codex 하네스 어댑터 — user-level **제거**(install.mjs 의 정확한 역연산).
// uninstall = 머신에서 lively 셋업을 **영구 제거**. incognito(LIVELY_OFF, 일시 off)와 다르다.
//
// 하는 일(전부 idempotent · surgical · 백업 먼저):
//  (1) ~/.codex/config.toml  ← lively-managed 센티넬 블록(BEGIN..END 포함)만 제거. 그 블록에 [mcp_servers.lively]
//        + [[hooks.*]] 가 모두 들어있다(install 이 한 블록으로 발행). 사용자 키(model/projects trust/tui/다른 mcp/hooks)는
//        한 바이트도 안 건드린다. 편집 전 config.toml.uninstall.bak 백업. 결과가 유효 TOML 인지 확인.
//        현재·옛(harness-kit) BEGIN 둘 다 인식(R3 리네임 마이그레이션 — 라이브 머신은 옛 마커 사용 중).
//  (2) ~/.codex/AGENTS.md  ← install 이 AG_BEGIN/END 센티넬로 org-context 를 **비파괴 머지**한 파일. 그 블록만 surgical 제거.
//        (센티넬 밖 사용자 글로벌 지침은 보존. 센티넬이 없으면 사용자 파일로 보고 보존. 블록 제거 후 내용이 비면 파일 삭제 — 모두 백업 후.)
//  (3) MCP 등록 해제: 블록 strip 으로 [mcp_servers.lively] 가 빠지지만, `codex mcp remove lively` 도 시도(있으면). 에러 무시.
//
// 공유 자산(~/.lively/*)은 여기서 안 지운다 — 공통 정리(setup/uninstall.mjs)가 담당.
//
// 사용법: node adapters/codex/uninstall.mjs [--dry-run]
// 샌드박스/테스트: env LIVELY_HOME=<dir> 로 HOME 리다이렉트(라이브 보호). 미지정 시 os.homedir().

import {
  readFileSync, writeFileSync, existsSync, mkdirSync, copyFileSync, rmSync, realpathSync,
} from "node:fs";
import { homedir } from "node:os";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const HOME = process.env.LIVELY_HOME || homedir();
const LIVELY = join(HOME, ".lively");
const CODEX = join(HOME, ".codex");

// install.mjs 와 동일한 센티넬 리터럴(역연산이므로 정확히 일치해야 함).
const BEGIN = "# >>> lively-managed (auto-generated by workflow-std/adapters/codex — do not edit) >>>";
const END = "# <<< lively-managed <<<";
// R3 리네임 마이그레이션: 옛 제품명(harness-kit)으로 깐 블록도 인식(라이브 dogfood 머신이 이 옛 마커 사용 중).
const LEGACY_BEGINS = [
  "# >>> lively-managed (auto-generated by lively-harness-kit/adapters/codex — do not edit) >>>",
];

const DRY = process.argv.includes("--dry-run");
const log = (s) => console.log(s);

// 센티넬 블록(BEGIN..END 포함)을 제거하고 나머지(사용자 본문)를 돌려준다.
//  install 의 stripManaged 와 동일 알고리즘 — 손상 마커(END 없음)도 BEGIN 한 줄만 떼고 아래 보존(클로버 금지).
export function stripManagedBlock(text) {
  let bi = text.indexOf(BEGIN);
  if (bi === -1) {
    for (const lb of LEGACY_BEGINS) {
      const li = text.indexOf(lb);
      if (li !== -1) { bi = li; break; }
    }
  }
  if (bi === -1) return { user: text, hadManaged: false };
  const ei = text.indexOf(END, bi);
  if (ei === -1) {
    // END 손상 — BEGIN 줄만 제거, 그 아래 사용자 키 보존.
    const eol = text.indexOf("\n", bi);
    const after = eol === -1 ? "" : text.slice(eol + 1);
    return { user: (text.slice(0, bi) + after).replace(/\n{3,}/g, "\n\n").trim() + "\n", hadManaged: true };
  }
  const before = text.slice(0, bi);
  const after = text.slice(ei + END.length);
  const user = (before + after).replace(/\n{3,}/g, "\n\n").trim();
  return { user: user ? user + "\n" : "", hadManaged: true };
}

// 결과 TOML 의 최소 sanity check(zero-dep — 정식 파서 없이): lively 잔재가 없고,
//  센티넬 마커가 안 남았는지 확인. (codex 가 실제 파싱 — 여기선 surgical 제거의 안전성만 검증.)
function looksValidAfterStrip(userBody) {
  if (userBody.includes(BEGIN) || LEGACY_BEGINS.some((b) => userBody.includes(b)) || userBody.includes(END)) {
    return { ok: false, why: "센티넬 마커 잔존(블록 제거 불완전)" };
  }
  if (/^\s*\[mcp_servers\.lively\]\s*$/m.test(userBody)) {
    return { ok: false, why: "[mcp_servers.lively] 잔존(블록 밖 사용자 정의? 수동 확인 필요)" };
  }
  return { ok: true };
}

export function uninstallCodexConfig({ dry = DRY } = {}) {
  const cfgPath = join(CODEX, "config.toml");
  if (!existsSync(cfgPath)) {
    log("  · ~/.codex/config.toml 없음 — 건너뜀");
    return false;
  }
  const raw = readFileSync(cfgPath, "utf8");
  const { user, hadManaged } = stripManagedBlock(raw);
  if (!hadManaged) {
    log("  · ~/.codex/config.toml — lively 센티넬 블록 없음(이미 제거됨/미설치). 무수정");
    return false;
  }
  const check = looksValidAfterStrip(user);
  if (!check.ok) {
    log(`  ⚠️ ~/.codex/config.toml — 블록 제거 후 이상(${check.why}) — 무수정(수동 확인 필요)`);
    return false;
  }
  if (dry) {
    log("  [dry-run] ~/.codex/config.toml — lively-managed 블록(BEGIN..END, [mcp_servers.lively]+[[hooks.*]]) 제거 예정 · 사용자 키 보존");
    return true;
  }
  // 백업 먼저(클로버 금지).
  const backupDir = join(LIVELY, "backups");
  try {
    mkdirSync(backupDir, { recursive: true });
    copyFileSync(cfgPath, join(backupDir, "config.toml.codex.uninstall.bak"));
  } catch (e) {
    try { copyFileSync(cfgPath, cfgPath + ".uninstall.bak"); }
    catch (e2) { console.error(`✗ config.toml 백업 실패 — 중단(클로버 금지): ${e.message} / ${e2.message}`); process.exit(1); }
  }
  if (user.trim()) {
    writeFileSync(cfgPath, user);
    log("  ✓ ~/.codex/config.toml — lively-managed 블록 제거(사용자 키 보존, 백업: backups/config.toml.codex.uninstall.bak)");
  } else {
    // 블록 제거 후 사용자 키가 하나도 없음 → lively 전용이었음. 0바이트 잔재 대신 파일 삭제(설치전상태=파일없음 복구). AGENTS.md 와 동일 패턴.
    rmSync(cfgPath, { force: true });
    log("  ✓ ~/.codex/config.toml 삭제(lively 전용이었음 — 빈 파일 잔재 방지, 백업됨)");
  }
  return true;
}

// ~/.codex/AGENTS.md — lively-managed 센티넬 블록만 surgical 제거(사용자 글로벌 지침/메모리 보존). 센티넬 없으면 보존.
const AG_BEGIN = "<!-- >>> lively-managed org-context (auto-generated by workflow-std — do not edit) >>> -->";
const AG_END = "<!-- <<< lively-managed <<< -->";
export function uninstallCodexAgents({ dry = DRY } = {}) {
  const agentsPath = join(CODEX, "AGENTS.md");
  if (!existsSync(agentsPath)) { log("  · ~/.codex/AGENTS.md 없음 — 건너뜀"); return; }
  let cur; try { cur = readFileSync(agentsPath, "utf8"); } catch { log("  ⚠️ ~/.codex/AGENTS.md 읽기 실패 — 무수정"); return; }
  const bi = cur.indexOf(AG_BEGIN);
  if (bi === -1) { log("  · ~/.codex/AGENTS.md — lively 센티넬 없음(사용자 파일/구버전) — 보존(파괴 안 함)"); return; }
  const ei = cur.indexOf(AG_END, bi);
  const user = (cur.slice(0, bi) + (ei === -1 ? "" : cur.slice(ei + AG_END.length))).replace(/\n{3,}/g, "\n\n").trim();
  if (dry) { log(`  [dry-run] ~/.codex/AGENTS.md — lively 블록 제거 ${user ? "(사용자 내용 보존)" : "(파일 비면 제거)"}`); return; }
  const backupDir = join(LIVELY, "backups");
  try { mkdirSync(backupDir, { recursive: true }); copyFileSync(agentsPath, join(backupDir, "codex-AGENTS.md.uninstall.bak")); } catch { /* 백업 실패해도 비파괴라 진행 */ }
  if (user) { writeFileSync(agentsPath, user + "\n"); log("  ✓ ~/.codex/AGENTS.md — lively 블록 제거(사용자 내용 보존, 백업됨)"); }
  else { rmSync(agentsPath, { force: true }); log("  ✓ ~/.codex/AGENTS.md 제거(lively 전용이었음, 백업됨)"); }
}

// codex mcp 등록 해제: install 은 [mcp_servers.lively] 를 **config.toml 블록 안**에만 두므로(별도 store 없음 —
//  확인: codex mcp list 가 config.toml 을 읽음), 위 블록 strip 이 곧 canonical deregister 다.
//  `codex mcp remove lively` 추가 시도는 (a) 이미 strip 됐으면 not-found no-op 이고 (b) codex 가 config.toml 을
//  TOML 라운드트립으로 재작성해 우리가 보존한 사용자 키 포맷을 흔들 위험이 있어, 기본은 호출하지 않는다.
//  자식 HOME 은 모듈 HOME 으로 명시 주입(샌드박스 격리) — 보강 호출을 켤 때만 의미 있음.
export function deregisterCodexMcp({ dry = DRY } = {}) {
  // config.toml 블록 strip 이 등록 해제를 이미 완료. codex CLI 재작성 위험을 피하려 별도 remove 는 생략.
  log(`  · codex MCP 등록 해제: config.toml 블록 제거로 완료(codex mcp list 가 config.toml 만 읽음 — 별도 store 없음).`);
  if (dry) log(`  [dry-run] (참고) codex mcp remove lively 는 호출 안 함(블록 strip 이 canonical · CLI 재작성 위험 회피).`);
}

export function uninstallCodex(opts = {}) {
  log("▶ Codex 어댑터 user-level 제거");
  const changed = uninstallCodexConfig(opts);
  uninstallCodexAgents(opts);
  deregisterCodexMcp(opts);
  return changed;
}

//  ⚠ realpath 비교 — /tmp·/var(/private/* 심링크)에서 실행 시 import.meta.url≠argv[1] 로 main 이 조용히 스킵되던 버그(install 측 동형).
const DIRECT_RUN = (() => {
  try { return realpathSync(fileURLToPath(import.meta.url)) === realpathSync(process.argv[1] || ""); }
  catch { return true; }
})();
if (DIRECT_RUN) {
  uninstallCodex();
  log("✓ Codex 어댑터 제거 완료." + (DRY ? " (dry-run — 변경 없음)" : ""));
}
