#!/usr/bin/env node
// codex auto-approve reconcile 사양테스트 — "자동승인 목록 변경이 두 하네스에 같은 주기로 반영된다"(#1475).
//  claude 는 settings.json permissions.allow 를 매 세션 reconcile 하는데 codex 만 재설치까지 기다렸다.
//  오프라인·fs-only: HOME 을 샌드박스로 돌려(POSIX os.homedir() 는 $HOME 을 따른다) 실 ~/.codex 무접촉.
//  실행: node kit/hooks/codex-auto-approve.test.mjs   (npm test 체인에 자동 포함)
//
//  이 함수의 위험은 "안 되는 것"이 아니라 **"사용자의 codex 를 못 뜨게 만드는 것"** 이다(config.toml 이 깨지면
//  lively 뿐 아니라 그 사람의 모든 MCP·훅이 죽는다). 그래서 단언은 목록 반영뿐 아니라 ⑤⑥(무배선·사용자영역
//  불가침)과 ⑧(실제 codex 로드)까지 본다.
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync, statSync } from "node:fs";
import { tmpdir, homedir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { applySandboxEnv } from "../testlib/os-sandbox.mjs";
import { offlineLivelyEnv } from "../testlib/os-sandbox.mjs";

const SANDBOX = mkdtempSync(join(tmpdir(), "codex-aa-test-"));
const REAL_HOME = homedir();
applySandboxEnv({ home: SANDBOX });  // os.homedir() 리다이렉트 — POSIX(HOME)·윈도우(USERPROFILE) 양쪽(#1510)
process.env.LIVELY_HOME = SANDBOX;
const CODEX = join(SANDBOX, ".codex");
const CFG = join(CODEX, "config.toml");
// env 설정 **후** 동적 import — 모듈 상수가 샌드박스 기준으로 굳는다.
const { reconcileCodexAutoApprove } = await import("./session-preload.mjs");

let pass = 0, fail = 0;
const ok = (n) => { pass++; console.log(`ok  ${n}`); };
const bad = (n, why) => { fail++; console.error(`FAIL ${n} — ${why}`); };
const digest = (p) => { try { return createHash("sha256").update(readFileSync(p)).digest("hex"); } catch { return "(none)"; } };
const REAL_CFG = join(REAL_HOME, ".codex", "config.toml");
const REAL_BEFORE = digest(REAL_CFG);   // ⓪ 배선 단언 — 실 홈 무접촉

const BEGIN = "# >>> lively-managed (auto-generated by workflow-std/adapters/codex — do not edit) >>>";
const END = "# <<< lively-managed <<<";
const USER_HEAD = 'model = "gpt-5.5"\n\n[tui]\ntheme = "one-half-light"\n\n';
const USER_TAIL = '\n[[hooks.Stop]]\n[[hooks.Stop.hooks]]\ntype = "command"\ncommand = "echo mine"\n';
// 설치기가 만드는 것과 같은 모양의 관리 블록(승인 테이블은 tools 인자로).
function writeCfg(tools = [], { managed = true } = {}) {
  mkdirSync(CODEX, { recursive: true });
  const toolLines = tools.flatMap((t) => [`[mcp_servers.lively.tools.${t}]`, 'approval_mode = "approve"', ""]);
  const block = managed ? [
    BEGIN, "",
    "[mcp_servers.lively]", 'command = "/x/.lively/bin/lively"', 'args = ["mcp"]', "",
    "[mcp_servers.lively.env]", 'LIVELY_HARNESS = "codex"', "",
    ...toolLines,
    "[[hooks.SessionStart]]", 'matcher = "startup|resume|clear"',
    "[[hooks.SessionStart.hooks]]", 'type = "command"', 'command = "node hook.mjs"', "timeout = 10", "",
    END,
  ].join("\n") + "\n" : "";
  writeFileSync(CFG, USER_HEAD + block + USER_TAIL);
}
const cfg = () => readFileSync(CFG, "utf8");
const approvedTools = (s) => (s.match(/\[mcp_servers\.lively\.tools\.([A-Za-z0-9_-]+)\]/g) || []).map((x) => x.slice("[mcp_servers.lively.tools.".length, -1)).sort();
const full = (t) => `mcp__lively__${t}`;

// ── B1 목록 추가(빈 → 2) ───────────────────────────────────────────────────
writeCfg([]);
{
  const changed = reconcileCodexAutoApprove([full("whoami"), full("knowledge_save")]);
  const got = approvedTools(cfg());
  changed && got.join(",") === "knowledge_save,whoami"
    ? ok("B1 목록 추가 → 승인 테이블 생성") : bad("B1 추가", `changed=${changed} got=${got.join(",")}`);
}

// ── B2 목록 축소(2 → 1) = 회수 ─────────────────────────────────────────────
{
  const changed = reconcileCodexAutoApprove([full("whoami")]);
  const got = approvedTools(cfg());
  changed && got.join(",") === "whoami"
    ? ok("B2 목록 축소 → 빠진 툴 회수") : bad("B2 회수", `changed=${changed} got=${got.join(",")}`);
}

// ── B3 전부 비움 → 승인 0, 배선은 그대로 ───────────────────────────────────
{
  reconcileCodexAutoApprove([]);
  const s = cfg();
  approvedTools(s).length === 0 && /\[\[hooks\.SessionStart\]\]/.test(s) && /\[mcp_servers\.lively\]/.test(s)
    ? ok("B3 빈 목록 → 승인 0, MCP·훅 배선 유지") : bad("B3 비움", approvedTools(s).join(","));
}

// ── B4 변경 없음 → 파일 무수정(불필요한 write 금지) ────────────────────────
writeCfg(["whoami"]);
{
  const before = digest(CFG);
  const changed = reconcileCodexAutoApprove([full("whoami")]);
  !changed && digest(CFG) === before
    ? ok("B4 동일 목록 → 무기록(파일 지문 불변)") : bad("B4 무변경", `changed=${changed} 지문변경=${digest(CFG) !== before}`);
}

// ── B5 센티넬 없음(미배선) → 절대 안 건드린다 ──────────────────────────────
writeCfg([], { managed: false });
{
  const before = digest(CFG);
  const changed = reconcileCodexAutoApprove([full("whoami")]);
  !changed && digest(CFG) === before
    ? ok("B5 미배선 config → 무수정") : bad("B5 미배선", "관리 블록이 없는데 파일을 건드렸다");
}

// ── B6 사용자 영역 불가침 ──────────────────────────────────────────────────
writeCfg([]);
{
  reconcileCodexAutoApprove([full("whoami"), full("db_query")]);
  const s = cfg();
  s.startsWith(USER_HEAD) && s.includes('command = "echo mine"') && /^theme = "one-half-light"$/m.test(s)
    ? ok("B6 센티넬 밖 사용자 키·자기 훅 보존") : bad("B6 사용자 영역", "센티넬 밖이 바뀌었다");
}

// ── B7 TOML 키로 못 쓰는 이름(경계) → 조용히 제외 ──────────────────────────
writeCfg([]);
{
  reconcileCodexAutoApprove([full("whoami"), full("bad.name"), full("also bad"), "mcp__other__tool", "쓰레기"]);
  const got = approvedTools(cfg());
  got.join(",") === "whoami"
    ? ok("B7 잡값·비안전 키 제외(안전한 것만 반영)") : bad("B7 키 안전성", got.join(","));
}

// ── B8 결과를 실제 codex 가 로드하나(있을 때만) ────────────────────────────
{
  writeCfg([]);
  reconcileCodexAutoApprove([full("whoami"), full("knowledge_save")]);
  const probe = spawnSync("codex", ["mcp", "list"], { env: { ...process.env, ...offlineLivelyEnv(), CODEX_HOME: CODEX }, encoding: "utf8" });
  if (probe.error) console.log("skip B8 codex 미설치 — 실파싱 검증 생략");
  else {
    const out = `${probe.stdout || ""}${probe.stderr || ""}`;
    !/failed to load configuration/i.test(out) && /lively/.test(out)
      ? ok("B8 실제 codex 가 갱신된 config.toml 을 로드") : bad("B8 codex 실파싱", out.split("\n").slice(0, 5).join(" | "));
  }
}

// ⓪ 재검
digest(REAL_CFG) === REAL_BEFORE ? ok("⓪ 실 ~/.codex/config.toml 무접촉") : bad("⓪ 샌드박스 계약", "실 홈이 변경됐다");

rmSync(SANDBOX, { recursive: true, force: true });
console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
