#!/usr/bin/env node
// Grok Build 하네스 어댑터 — user-level **제거**(setup/user-install.mjs 의 installGrok 역연산, #1701).
// uninstall = 머신에서 lively 셋업을 **영구 제거**. incognito(LIVELY_OFF, 일시 off)와 다르다.
//
// 하는 일(전부 idempotent · surgical · 백업 먼저):
//  (1) <grok home>/hooks/lively-grok.json  ← 삭제. **파일이 통째로 우리 것**(hook-file 배선)이라 surgical 판단이
//        필요 없다 — 사용자의 다른 훅 파일은 형제라 불가침.
//  (2) <grok home>/config.toml             ← lively-managed 센티넬 블록([mcp_servers.lively] 등)만 제거. 사용자 키 보존.
//  (3) <grok home>/rules/lively.md         ← 삭제(org-context 센티넬 블록만 담긴 우리 파일).
//  auto-approve 는 ~/.claude/settings.json(claude 표면)이 정본이라 여기서 안 만진다 — grok 은 compat 로 읽었을 뿐.
//
// 공유 자산(~/.lively/*)은 여기서 안 지운다 — 공통 정리(setup/uninstall.mjs)가 담당.
//
// 사용법: node adapters/grok/uninstall.mjs [--dry-run]
// 샌드박스/테스트: env LIVELY_HOME=<dir> 로 HOME 리다이렉트(라이브 보호). 미지정 시 os.homedir().

import { readFileSync, writeFileSync, existsSync, mkdirSync, copyFileSync, rmSync, realpathSync } from "node:fs";
import { homedir } from "node:os";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const HOME = process.env.LIVELY_HOME || homedir();
const LIVELY = join(HOME, ".lively");
// 설치기와 **같은 계산**이어야 역연산이 성립한다 — GROK_HOME > ~/.grok, LIVELY_HOME 격리 시 GROK_HOME 무시(#1701).
const GROK = process.env.LIVELY_HOME ? join(HOME, ".grok") : (process.env.GROK_HOME || join(HOME, ".grok"));
const GROK_HOOKS_FILE = join(GROK, "hooks", "lively-grok.json");
const GROK_RULES_FILE = join(GROK, "rules", "lively.md");
// install 의 GRK_BEGIN/END 와 동일 리터럴(설치↔제거 대칭 불변식).
const GRK_BEGIN = "# >>> lively-managed (auto-generated by workflow-std/adapters/grok — do not edit) >>>";
const GRK_END = "# <<< lively-managed <<<";

const log = (s) => console.log(s);

function backup(path, name) {
  try {
    const dir = join(LIVELY, "backups");
    mkdirSync(dir, { recursive: true });
    if (existsSync(path)) copyFileSync(path, join(dir, name));
  } catch { /* 백업 실패해도 아래 편집은 surgical(비파괴) */ }
}

// (1) 훅 파일 제거 — 통째로 우리 것.
export function removeHooksFile({ dry = false } = {}) {
  if (!existsSync(GROK_HOOKS_FILE)) { log("  · ~/.grok/hooks/lively-grok.json 없음 — 건너뜀"); return 0; }
  if (dry) { log("  [dry-run] ~/.grok/hooks/lively-grok.json 제거 예정(사용자 훅 파일 불가침)"); return 1; }
  try { rmSync(GROK_HOOKS_FILE, { force: true }); }
  catch (e) { log(`  ⚠️ 훅 파일 제거 실패: ${e.message}`); return 0; }
  log("  ✓ ~/.grok/hooks/lively-grok.json 제거(사용자 훅 파일 불가침)");
  return 1;
}

// (2) config.toml 의 lively-managed 센티넬 블록만 제거(사용자 키 보존 — codex 어댑터와 동형).
export function removeConfigBlock({ dry = false } = {}) {
  const cfgPath = join(GROK, "config.toml");
  if (!existsSync(cfgPath)) { log("  · ~/.grok/config.toml 없음 — 건너뜀"); return 0; }
  let raw;
  try { raw = readFileSync(cfgPath, "utf8"); }
  catch { log(`  ⚠️ ${cfgPath.replace(HOME, "~")} 읽기 실패 — 무수정`); return 0; }
  const bi = raw.indexOf(GRK_BEGIN);
  if (bi === -1) { log("  · ~/.grok/config.toml — lively 블록 없음(이미 제거됨/미설치). 무수정"); return 0; }
  const ei = raw.indexOf(GRK_END, bi);
  let next;
  if (ei === -1) { const eol = raw.indexOf("\n", bi); const after = eol === -1 ? "" : raw.slice(eol + 1); next = (raw.slice(0, bi) + after).replace(/\n{3,}/g, "\n\n"); }
  else next = (raw.slice(0, bi) + raw.slice(ei + GRK_END.length)).replace(/\n{3,}/g, "\n\n");
  if (dry) { log("  [dry-run] ~/.grok/config.toml — lively-managed 블록 제거 예정(사용자 키 보존)"); return 1; }
  backup(cfgPath, "config.toml.grok.uninstall.bak");
  try {
    if (next.trim()) writeFileSync(cfgPath, next.replace(/\s+$/, "") + "\n");
    else rmSync(cfgPath, { force: true });   // 우리 블록이 전부였다 — 빈 파일을 남기지 않는다(백업됨)
  } catch (e) { log(`  ⚠️ config.toml 정리 실패: ${e.message}`); return 0; }
  log("  ✓ ~/.grok/config.toml — lively-managed 블록 제거(사용자 키 보존, 백업됨)");
  return 1;
}

// (3) rules/lively.md 제거 — 파일이 통째로 우리 것.
export function removeRulesFile({ dry = false } = {}) {
  if (!existsSync(GROK_RULES_FILE)) { log("  · ~/.grok/rules/lively.md 없음 — 건너뜀"); return 0; }
  if (dry) { log("  [dry-run] ~/.grok/rules/lively.md 제거 예정(다른 rules 파일 불가침)"); return 1; }
  try { rmSync(GROK_RULES_FILE, { force: true }); }
  catch (e) { log(`  ⚠️ rules 제거 실패: ${e.message}`); return 0; }
  log("  ✓ ~/.grok/rules/lively.md 제거(다른 rules 파일 불가침)");
  return 1;
}

export function uninstallGrok({ dry = false } = {}) {
  log("  ── Grok Build ──");
  return removeHooksFile({ dry }) + removeConfigBlock({ dry }) + removeRulesFile({ dry });
}

// 직접 실행일 때만 수행 — 판정 불가면 **실행하지 않는다**(제거는 안 도는 편이 안전 — 타 어댑터와 동일 패턴).
const DIRECT_RUN = (() => {
  try { return realpathSync(fileURLToPath(import.meta.url)) === realpathSync(process.argv[1] || ""); }
  catch { return false; }
})();
if (DIRECT_RUN) uninstallGrok({ dry: process.argv.includes("--dry-run") });
