#!/usr/bin/env node
// workflow-std 생성기 — 조직콘텐츠(org/ · members/ · memory/)를 입력받아
//   발행 아티팩트(설치 번들)를 조립한다: CLAUDE.md(@import) + AGENTS.md(inline) + 참조 md
//   + setup/ + register-clients.sh + 선택한 하네스의 설정(.claude/...).
// org-agnostic · zero-dep. 제품 파일(hooks/·adapters/·setup/·template-org/)은 KIT_ROOT, 조직콘텐츠는 --org(ORG_ROOT).
//
//   발행:  node generator/build-context.mjs --org <org-content-dir> --publish <out-dir> [--harness claude] [--emit-root]
//   새 조직 init:  node generator/build-context.mjs --init <new-org-dir> [--force]   (template-org → 새 독립 레포 복사)
//   조직콘텐츠 점검(doctor):  node generator/build-context.mjs --check <org-content-dir>   (template-org 대비 차이·린트, 읽기전용)
//   훅만 설치(독푸드):  node generator/build-context.mjs --org <dir> --install-hooks <dir> [<dir>…]
//
//  - Claude Code: CLAUDE.md 를 읽고 @import 지원 → import 로 합성
//  - Codex / openclaw: AGENTS.md 만 읽고 @import 미지원 → 내용 inline
//
// 두 개의 분리된 루트(핵심 리팩터):
//  - KIT_ROOT = 이 스크립트의 ../  (제품: hooks/·adapters/·setup/·template-org/·vendored register-clients.sh)
//  - ORG_ROOT = resolve(--org)     (조직콘텐츠: org/·members/·memory/)
//  generate()/collectArtifactFiles 는 ORG_ROOT, emitHooks/setup/template-org 복사는 KIT_ROOT 에서 해석한다.
//
// 조직콘텐츠 진화 모델(설계 R3): template-org 는 새 조직의 1회성 INIT 소스일 뿐(베이스 아님).
//  --init 이 template-org 를 새 독립 레포로 복사 → 그 레포는 조직 소유, 이후 template-org 를 다시 당기지 않음
//  (별개 레포 = git-pull 충돌 0). 진짜 진화 문제(새 제품이 새 필드를 기대)는: (1) 생성기가 누락 파일/필드에
//  관대(누락 → 기본/스킵, 에러 아님) · (2) --check(doctor) 가 template-org 대비 차이를 보고 · (3) template-org VERSION/CHANGELOG.

import {
  readFileSync,
  writeFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  rmSync,
  copyFileSync,
  chmodSync,
  cpSync,
  statSync,
} from "node:fs";
import { join, dirname, resolve, basename, relative } from "node:path";
import { fileURLToPath } from "node:url";

// ── 두 루트 ──────────────────────────────────────────────────────
// KIT_ROOT = 제품 루트. 기본은 이 스크립트의 ../ (sibling 레이아웃). 게이트웨이가
// 다른 경로에서 subprocess 로 호출할 때를 위해 WORKFLOW_STD_DIR env 로 오버라이드 가능(호환·무해).
const KIT_ROOT = process.env.WORKFLOW_STD_DIR
  ? resolve(process.env.WORKFLOW_STD_DIR)
  : join(dirname(fileURLToPath(import.meta.url)), "..");
const kitAbs = (p) => join(KIT_ROOT, p);

const HEADER =
  "<!-- AUTO-GENERATED by workflow-std/generator/build-context.mjs — 직접 수정 금지. 소스: org/ · members/ · memory/ -->";

// inline 용: 앞쪽 HTML 주석 + frontmatter 제거
const strip = (md) =>
  md.replace(/^<!--[\s\S]*?-->\s*/, "").replace(/^---[\s\S]*?---\s*/, "").trim();

// 개인 레이어(선택, gitignore): members/local.md  — 각자 _template.md 복사해서 채움
const PERSONAL = "members/local.md";

// 조직 표시 이름(org-agnostic). 제품에 라이블리 등 특정 조직 라벨을 박지 않는다(설계 D1).
//  우선순위: --org-name(또는 인자) > org/org-defaults.md frontmatter `org-name:` > 첫 H1(`# …`) > basename(orgRoot).
//  마지막 폴백은 orgRoot 의 basename(중립값) — 어떤 조직콘텐츠에도 특정 회사명이 새지 않는다.
//  "컨텍스트"·"공통 컨텍스트" 등 흔한 접미사는 헤더에서 우리가 다시 붙이므로 떼어 정규화.
function deriveOrgName(orgRoot, override) {
  if (override && String(override).trim()) return String(override).trim();
  try {
    const md = readFileSync(join(orgRoot, "org/org-defaults.md"), "utf8");
    const fm = md.match(/^---\n([\s\S]*?)\n---/);
    if (fm) {
      const m = fm[1].match(/^\s*org-name\s*:\s*(.+?)\s*$/m);
      if (m && m[1].trim()) return m[1].trim().replace(/^["']|["']$/g, "");
    }
    const body = md.replace(/^<!--[\s\S]*?-->\s*/, "").replace(/^---[\s\S]*?---\s*/, "");
    const h1 = body.match(/^#\s+(.+?)\s*$/m);
    if (h1) return h1[1].replace(/\s*(공통\s*)?컨텍스트\s*$/, "").trim() || h1[1].trim();
  } catch { /* 폴백으로 */ }
  // 최후 폴백: 디렉터리명(예: ../acme-org → "acme-org"). 특정 회사명 하드코딩 금지.
  return basename(resolve(orgRoot)) || "조직";
}

// ── 생성 (CLAUDE.md @import + AGENTS.md inline) — ORG_ROOT 기준 ──
// personal=false: 배포 아티팩트용 — 빌더 머신에 local.md 가 있어도 절대 합성하지 않음.
// orgName: 헤더 표시명(미지정 시 deriveOrgName 으로 도출).
function generate(orgRoot, { personal = true, orgName } = {}) {
  const orgAbs = (p) => join(orgRoot, p);
  const orgRead = (p) => readFileSync(orgAbs(p), "utf8").trim();
  const orgHas = (p) => existsSync(orgAbs(p));
  const name = orgName || deriveOrgName(orgRoot);
  const header = `# ${name} 컨텍스트`;

  // 조직콘텐츠 진화에 관대: 표준 레이어 파일은 '있으면 합성, 없으면 스킵(경고)'.
  //  하드 요구는 org/org-defaults.md 하나뿐(없으면 합성할 게 없음 → 명확히 실패).
  //  managed-policy·MEMORY 가 없는(옛 template-init) 조직콘텐츠도 크래시 없이 빌드된다(R3 tolerant).
  const REQUIRED = "org/org-defaults.md";
  if (!orgHas(REQUIRED)) {
    console.error(`✗ 필수 조직콘텐츠 누락: ${REQUIRED} (조직 컨텍스트의 코어 — 없으면 합성할 내용이 없습니다)`);
    console.error("  새 조직콘텐츠라면 먼저:  node generator/build-context.mjs --init <dir>  로 골격을 만드세요.");
    process.exit(1);
  }

  const STD_LAYERS = ["org/managed-policy.md", "org/org-defaults.md", "memory/knowledge-index.md"];
  const imports = STD_LAYERS.filter((p) => orgHas(p));
  const skipped = STD_LAYERS.filter((p) => !orgHas(p));
  for (const p of skipped) console.warn(`  ⚠️ 선택 레이어 누락 → 스킵: ${p}`);
  if (personal && orgHas(PERSONAL)) imports.push(PERSONAL);

  const claudeMd = [HEADER, "", header, "", ...imports.map((p) => `@${p}`), ""].join(
    "\n",
  );

  const sections = [
    HEADER,
    header,
    orgHas("org/managed-policy.md") ? strip(orgRead("org/managed-policy.md")) : "",
    strip(orgRead("org/org-defaults.md")),
    orgHas("memory/knowledge-index.md") ? strip(orgRead("memory/knowledge-index.md")) : "",
  ];
  if (personal && orgHas(PERSONAL)) sections.push("# 개인 레이어\n\n" + strip(orgRead(PERSONAL)));
  const agentsMd = sections.filter(Boolean).join("\n\n") + "\n";

  return { claudeMd, agentsMd, imports, orgName: name };
}

// 어댑터가 ~/.lively/context.md 로 발행할 정적 org-context 문자열.
//  = generate({personal:false}).agentsMd 에서 선두 HEADER 주석 한 줄 제거(토큰/시크릿 없음).
//  세션별 라이브 현황은 session-preload.mjs 가 동적으로 붙인다(여기 굽지 않음).
//  org 표시명도 함께 반환 — 어댑터가 ~/.lively/org-name 으로 발행해 preload 가 라이브 헤더에 쓴다.
export function buildStaticContext(orgRoot, orgName) {
  const r = generate(resolve(orgRoot), { personal: false, orgName });
  return {
    context: r.agentsMd.replace(/^<!--[\s\S]*?-->\s*/, "").trim() + "\n",
    orgName: r.orgName,
  };
}

// org 표시명만 도출(어댑터/도구가 가볍게 재사용).
export { deriveOrgName };

// ── 레포 루트 생성 (--emit-root 일 때만 — 소스 레포 내부 실행 편의) ──
function emitRoot(orgRoot, orgName) {
  const orgHas = (p) => existsSync(join(orgRoot, p));
  const { claudeMd, agentsMd, imports } = generate(orgRoot, { orgName });
  writeFileSync(join(orgRoot, "CLAUDE.md"), claudeMd);
  writeFileSync(join(orgRoot, "AGENTS.md"), agentsMd);

  const bytes = Buffer.byteLength(agentsMd, "utf8");
  const warn = bytes > 32 * 1024 ? "  ⚠️ Codex 32KiB 초과!" : "";
  console.log(`✓ ${basename(orgRoot)}/CLAUDE.md  (@import ${imports.length}개)`);
  console.log(`✓ ${basename(orgRoot)}/AGENTS.md  (${(bytes / 1024).toFixed(1)} KiB)${warn}`);
  console.log(
    `  개인 레이어: ${orgHas(PERSONAL) ? PERSONAL : "(없음 — members/_template.md 복사해 members/local.md 생성)"}`,
  );
}

// ── 발행 (--publish <target>): 설치 번들 아티팩트 조립 ──

// 복사 목록 도출: CLAUDE.md 의 @import 줄 파싱(하드코딩 금지)
// + 각 import 된 md 안의 상대 md 링크를 1-depth follow (외부 URL·앵커 제외)
// — MEMORY.md 가 링크하는 memory/*.md 가 고아가 되지 않게. (ORG_ROOT 기준)
function collectArtifactFiles(claudeMd, orgRoot) {
  const orgHas = (p) => existsSync(join(orgRoot, p));
  const orgRead = (p) => readFileSync(join(orgRoot, p), "utf8").trim();
  const importPaths = [...claudeMd.matchAll(/^@(.+)$/gm)].map((m) => m[1].trim());
  const files = new Set(importPaths);
  for (const p of importPaths) {
    if (!orgHas(p)) continue;
    const md = orgRead(p);
    for (const m of md.matchAll(/\]\(([^)#:]+\.md)\)/g)) {
      const linked = join(dirname(p), m[1]);
      if (orgHas(linked)) files.add(linked);
    }
  }
  return [...files];
}

const GENERATED_NOTE = (src, orgLabel) =>
  `# 생성물 — 수정 금지. 원본: ${src} (원본 수정 후 ${orgLabel} 에서 재발행)`;

// .sh: shebang 다음 줄에 생성물 헤더 삽입
function copyShWithHeader(srcAbs, destAbs, srcLabel, orgLabel) {
  const text = readFileSync(srcAbs, "utf8");
  const lines = text.split("\n");
  const note = GENERATED_NOTE(srcLabel, orgLabel);
  if (lines[0]?.startsWith("#!")) lines.splice(1, 0, note);
  else lines.unshift(note);
  writeFileSync(destAbs, lines.join("\n"));
  chmodSync(destAbs, 0o755);
}

// .mjs: '//' 주석 헤더(셸 '#' 주석은 .mjs 에서 문법 오류) — shebang 있으면 다음 줄 삽입
function copyMjsWithHeader(srcAbs, destAbs, srcLabel, orgLabel) {
  const text = readFileSync(srcAbs, "utf8");
  const lines = text.split("\n");
  const note = "// " + GENERATED_NOTE(srcLabel, orgLabel).replace(/^# /, "");
  if (lines[0]?.startsWith("#!")) lines.splice(1, 0, note);
  else lines.unshift(note);
  writeFileSync(destAbs, lines.join("\n"));
  chmodSync(destAbs, 0o755);
}

// .ps1: Buffer 로 읽어 UTF-8 BOM(efbbbf) 보존 — BOM 직후 첫 줄에 헤더 삽입
function copyPs1WithHeader(srcAbs, destAbs, srcLabel, orgLabel) {
  const buf = readFileSync(srcAbs);
  const hasBom = buf.length >= 3 && buf[0] === 0xef && buf[1] === 0xbb && buf[2] === 0xbf;
  const bom = hasBom ? buf.subarray(0, 3) : Buffer.alloc(0);
  const body = hasBom ? buf.subarray(3) : buf;
  const header = Buffer.from(GENERATED_NOTE(srcLabel, orgLabel) + "\n", "utf8");
  writeFileSync(destAbs, Buffer.concat([bom, header, body]));
}

// ── 훅 패키지 에밋 (PROJECT-DIR 템플릿 — '번들 폴더에서 실행' 병행 경로용) ──
// hooks/*.mjs 3종을 <target>/.claude/hooks/ 에 헤더 부착 복사하고(소스=KIT_ROOT),
// hooks/settings-hooks.json(PROJECT-DIR 템플릿, $CLAUDE_PROJECT_DIR 경로)을
// <target>/.claude/settings.json 에 비파괴 머지한다(idempotent).
//  ※ user-level(~/.claude) 절대경로 변형은 claude 어댑터가 emit — 여기 아님.
//  run-custom.mjs = 커스텀 훅 런너(발행물에 동봉 → user-install 이 ~/.lively/hooks 로 복사·등록).
const HOOK_SCRIPTS = ["session-preload.mjs", "work-flag.mjs", "stop-writeback-gate.mjs", "run-custom.mjs"];

function emitHooks(targetDir, orgLabel) {
  const hooksDir = join(targetDir, ".claude", "hooks");
  mkdirSync(hooksDir, { recursive: true });
  for (const f of HOOK_SCRIPTS) {
    copyMjsWithHeader(kitAbs(join("hooks", f)), join(hooksDir, f), `workflow-std/hooks/${f}`, orgLabel);
  }

  const template = JSON.parse(readFileSync(kitAbs("hooks/settings-hooks.json"), "utf8"));
  const settingsPath = join(targetDir, ".claude", "settings.json");
  let cur = {};
  if (existsSync(settingsPath)) {
    try {
      cur = JSON.parse(readFileSync(settingsPath, "utf8"));
    } catch {
      console.warn(`  ⚠️ ${settingsPath} JSON 파싱 실패 — hooks 머지 건너뜀(기존 파일 무수정)`);
      console.log(`  ✓ .claude/hooks/ (${HOOK_SCRIPTS.length}개 스크립트만 설치)`);
      return;
    }
  }
  if (cur === null || typeof cur !== "object" || Array.isArray(cur)) {
    console.warn(`  ⚠️ ${settingsPath} 가 객체가 아님 — hooks 머지 건너뜀`);
    return;
  }
  cur.hooks = cur.hooks && typeof cur.hooks === "object" && !Array.isArray(cur.hooks) ? cur.hooks : {};
  const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);
  for (const [event, entries] of Object.entries(template.hooks)) {
    const arr = Array.isArray(cur.hooks[event]) ? cur.hooks[event] : [];
    for (const entry of entries) {
      // command 문자열 기준 idempotent: 같은 command 를 가진 entry 가 이미 있으면 skip
      const cmds = new Set(entry.hooks.map((h) => h.command));
      const dup = arr.some((e) => (e.hooks ?? []).some((h) => cmds.has(h.command)) && same(e.matcher ?? null, entry.matcher ?? null));
      if (!dup) arr.push(entry);
    }
    cur.hooks[event] = arr;
  }
  writeFileSync(settingsPath, JSON.stringify(cur, null, 2) + "\n");
  console.log(`  ✓ .claude/settings.json (hooks 머지) + .claude/hooks/ (${HOOK_SCRIPTS.length}개)`);
}

const teamReadme = (publishLabel, orgLabel, orgName) => `# ${orgName} 팀 컨텍스트 (설치 묶음)

${orgName} 팀 컨텍스트 **설치 묶음**입니다. 게이트웨이 토큰게이트 \`/install\` 에서 받아 \`setup\` 을 한 번 돌리면(user-level 설치),
이후 **어느 폴더에서든** 하네스(Claude Code · Codex · openclaw)가 조직 컨텍스트+리플렉스를 받습니다.
(조직 맥락은 설치 시 1회 + 매 세션 게이트웨이에서 **라이브로** 받습니다 — 번들에 정적 콘텐츠를 굽지 않습니다.)

> **이 묶음은 생성물입니다 — 게이트웨이가 조직 DB(위키)에서 발행할 때마다 새로 만듭니다(git clone 아님).**
> 여기 파일을 직접 고치지 마세요. 조직콘텐츠 수정은 관리 웹 UI(\`/ui\`)에서.

## 사용법

가장 쉬운 길: 관리 페이지 \`[설치]\` 탭에서 본인 토큰을 발급하면 나오는 **한 줄 설치 명령**을 그대로 실행하세요(Mac/Windows 동일).

직접 받은 이 묶음으로 설치할 때:
1. 셋업 (한 번만, 재실행 안전 — user-level 설치):
   - **Mac:** 이 폴더에서 \`bash setup/setup-mac.sh\`
   - **Windows:** \`setup/setup-windows.ps1\` 우클릭 → "PowerShell에서 실행"
2. 이후 **자기 코드 레포 등 아무 폴더**에서 \`claude\` 실행 — 회사 맥락을 아는 상태로 시작됩니다.

업데이트는 설치/업데이트 명령 재실행(최신 묶음을 받음 — Mac \`[설치]\` 탭 / Windows \`setup/update-windows.ps1\`). 라이브 현황은 세션마다 자동 갱신됩니다.

## 개인 레이어 (선택)

\`members/_template.md\` 를 \`members/local.md\` 로 복사해 채우면 개인 선호를 둘 수 있습니다(gitignore — 커밋 안 됨).
단, 배포된 \`CLAUDE.md\` 는 \`members/local.md\` 를 자동 import 하지 않습니다 — 개인 레이어 합성이 필요하면
관리자(관리 웹 UI)에게 요청하세요.
`;

// ── 하네스별 publish-emit 인터페이스 ──────────────────────────────
// 단일 시그니처 emit({ target, orgLabel, copied }) — claude 와 (R2) codex 가 같은 모양을 공유한다.
// publish() 가 HARNESS_EMIT[harness] 로 dispatch. R2 는 codex emit 만 채우면 drop-in.
function emitClaudeArtifact({ target, orgLabel, copied }) {
  // PROJECT-DIR 템플릿 ('번들 폴더에서 실행' 병행 경로). user-level 절대경로는 어댑터 install 이 별도.
  emitHooks(target, orgLabel);
  copied.push(".claude/settings.json", ...HOOK_SCRIPTS.map((f) => `.claude/hooks/${f}`));
  // user-level 설치기 vendoring (D2/D3 헤드라인): kit 없이 '번들 → setup → 어디서든' 을 완성.
  //  발행물 .claude/hooks/*.mjs + AGENTS.md + .lively-org-name 만으로 ~/.lively + ~/.claude 머지.
  copyMjsWithHeader(
    kitAbs("setup/user-install.mjs"),
    join(target, "setup", "user-install.mjs"),
    "workflow-std/setup/user-install.mjs",
    orgLabel,
  );
  copied.push("setup/user-install.mjs");
  // user-level 제거기 vendoring (install/uninstall 대칭) — self-contained, kit 미의존. uninstall-mac.sh 가 이걸 부른다.
  copyMjsWithHeader(
    kitAbs("setup/user-uninstall.mjs"),
    join(target, "setup", "user-uninstall.mjs"),
    "workflow-std/setup/user-uninstall.mjs",
    orgLabel,
  );
  copied.push("setup/user-uninstall.mjs");
}

// Codex(R2): user-level 전달.
//  - kit-안 경로: adapters/codex/install.mjs (generator 의 buildStaticContext 사용) — setup-mac.sh 가 호출.
//  - 번들-안(발행물) 경로: 발행물 동봉 setup/user-install.mjs 가 --harness codex 로 호출되면 Codex 도 설치한다
//    (자체완결 — generator 미의존, 발행물 AGENTS.md + .claude/hooks/*.mjs 자산만으로 ~/.codex 설정).
//    → 별도 codex 어댑터를 발행물에 vendoring 하지 않는다(generator import 깨짐 방지). user-install.mjs 단일.
//  - 번들-안에서-실행(병행 경로): 발행물 루트 AGENTS.md 를 Codex 가 프로젝트-doc 로 네이티브 로드.
//  발행물에 codex 전용 추가 파일은 없다 — 컨텍스트 md + 공유 훅 + user-install.mjs(이미 claude emit 이 동봉)로 충분.
function emitCodexArtifact({ copied }) {
  const hasUserInstall = copied.includes("setup/user-install.mjs");
  console.log(
    `  ▶ harness=codex → user-level 은 발행물 동봉 user-install.mjs(--harness codex)${hasUserInstall ? "" : " ⚠️ user-install.mjs 미동봉 — claude 와 함께 발행하세요(--harness claude,codex)"} + 루트 AGENTS.md(병행 경로). codex 전용 추가 파일 없음.`,
  );
}

const HARNESS_EMIT = {
  claude: emitClaudeArtifact,
  codex: emitCodexArtifact,
};

// 다중 하네스 발행: --harness claude,codex → 두 emit 을 순서대로 실행(같은 발행물에 양쪽 설정 추가).
function dispatchEmit(harnessSpec, ctx) {
  const harnesses = String(harnessSpec).split(",").map((h) => h.trim()).filter(Boolean);
  const unknown = harnesses.filter((h) => !HARNESS_EMIT[h]);
  if (unknown.length) {
    console.error(`✗ 알 수 없는 harness: ${unknown.join(", ")} (${Object.keys(HARNESS_EMIT).join("|")})`);
    process.exit(1);
  }
  for (const h of harnesses) HARNESS_EMIT[h](ctx);
}

function publish(orgRoot, target, harness, orgName) {
  // harness 스펙을 '파일 쓰기 전에' 검증 — 알 수 없는 harness 면 부분 발행물(AGENTS.md/members/…)을
  //  남기지 않고 즉시 실패한다(부분 디렉토리 hygiene). dispatchEmit 이 끝에서 또 검증하지만 그땐 이미 늦다.
  const harnessNames = String(harness).split(",").map((h) => h.trim()).filter(Boolean);
  const unknownHarness = harnessNames.filter((h) => !HARNESS_EMIT[h]);
  if (!harnessNames.length || unknownHarness.length) {
    console.error(`✗ 알 수 없는 harness: ${(unknownHarness.length ? unknownHarness : [harness]).join(", ")} (${Object.keys(HARNESS_EMIT).join("|")})`);
    process.exit(1);
  }

  const orgLabel = basename(orgRoot);
  const publishLabel = basename(target);
  const orgAbs = (p) => join(orgRoot, p);
  const orgHas = (p) => existsSync(orgAbs(p));
  const name = orgName || deriveOrgName(orgRoot);

  // 아티팩트는 개인 레이어 제외로 생성
  const art = generate(orgRoot, { personal: false, orgName: name });
  mkdirSync(target, { recursive: true });

  // 타깃 클린 (idempotent 재발행) — .git 보존 + members/local.md(개인 레이어, gitignore) 보존.
  for (const ent of readdirSync(target)) {
    if (ent === ".git") continue;
    if (ent === "members") {
      let subs = null;
      try { subs = readdirSync(join(target, ent)); } catch { /* members 가 디렉토리가 아니면 통째 삭제로 폴백 */ }
      if (subs) {
        for (const sub of subs) {
          if (sub === "local.md") continue;
          rmSync(join(target, ent, sub), { recursive: true, force: true });
        }
        continue;
      }
    }
    rmSync(join(target, ent), { recursive: true, force: true });
  }

  const copied = [];
  const put = (rel, content) => {
    const dest = join(target, rel);
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, content);
    copied.push(rel);
  };

  // 루트 생성물
  put("CLAUDE.md", art.claudeMd);
  put("AGENTS.md", art.agentsMd);

  // @import 대상 + 1-depth 링크 md 복사 (상대경로 보존, ORG_ROOT 기준)
  for (const f of collectArtifactFiles(art.claudeMd, orgRoot)) {
    const dest = join(target, f);
    mkdirSync(dirname(dest), { recursive: true });
    copyFileSync(orgAbs(f), dest);
    copied.push(f);
  }

  // 개인 레이어 템플릿 + .gitignore (ORG_ROOT 기준)
  const tpl = "members/_template.md";
  if (orgHas(tpl)) {
    mkdirSync(join(target, "members"), { recursive: true });
    copyFileSync(orgAbs(tpl), join(target, tpl));
    copied.push(tpl);
  }
  put(".gitignore", "# 개인 레이어 — 각 머신/사람마다 다르므로 커밋하지 않음\nmembers/local.md\n");

  // setup/ — 전부 '생성물' 헤더 부착 복사 (소스=KIT_ROOT, 단일 출처 유지)
  const setupDir = join(target, "setup");
  mkdirSync(setupDir, { recursive: true });
  copyShWithHeader(kitAbs("setup/setup-mac.sh"), join(setupDir, "setup-mac.sh"), "workflow-std/setup/setup-mac.sh", orgLabel);
  copied.push("setup/setup-mac.sh");
  // 제거기 UX 래퍼(install 의 setup-mac.sh 와 대칭) — 발행물(번들)에선 self-contained user-uninstall.mjs 를 부른다.
  //  (user-uninstall.mjs 자체는 emitClaudeArtifact 에서 vendoring — user-install.mjs 와 대칭.)
  copyShWithHeader(kitAbs("setup/uninstall-mac.sh"), join(setupDir, "uninstall-mac.sh"), "workflow-std/setup/uninstall-mac.sh", orgLabel);
  copied.push("setup/uninstall-mac.sh");
  // 업데이트 UX 래퍼(install/uninstall 과 대칭, self-contained — 설치된 토큰으로 재페치·멱등 재설치).
  copyShWithHeader(kitAbs("setup/update-mac.sh"), join(setupDir, "update-mac.sh"), "workflow-std/setup/update-mac.sh", orgLabel);
  copied.push("setup/update-mac.sh");
  copyPs1WithHeader(
    kitAbs("setup/setup-windows.ps1"),
    join(setupDir, "setup-windows.ps1"),
    "workflow-std/setup/setup-windows.ps1",
    orgLabel,
  );
  copied.push("setup/setup-windows.ps1");
  // Windows 업데이트·제거(self-contained, ⚠ 미검증) — install/uninstall 대칭.
  for (const ps of ["update-windows.ps1", "uninstall-windows.ps1"]) {
    const src = kitAbs("setup/" + ps);
    if (!existsSync(src)) continue;
    copyPs1WithHeader(src, join(setupDir, ps), "workflow-std/setup/" + ps, orgLabel);
    copied.push("setup/" + ps);
  }

  // register-clients.sh — 게이트웨이 레포가 캐노니컬(GATEWAY_DIR 로 오버라이드).
  //  기본은 KIT_ROOT 옆의 context-ontology; 없으면 kit 에 vendoring 된 사본으로 폴백.
  const gatewayDir = process.env.GATEWAY_DIR || join(KIT_ROOT, "..", "context-ontology");
  const gwReg = join(gatewayDir, "scripts", "register-clients.sh");
  const vendored = kitAbs("setup/register-clients.sh");
  const regSrc = existsSync(gwReg) ? gwReg : vendored;
  const regSrcLabel = existsSync(gwReg) ? "context-ontology/scripts/register-clients.sh" : "workflow-std/setup/register-clients.sh (vendored)";
  if (!existsSync(regSrc)) {
    console.error(`✗ register-clients.sh 원본 없음: ${gwReg} (및 vendored 사본도 없음)`);
    console.error("  게이트웨이 레포 경로를 GATEWAY_DIR 환경변수로 지정하세요.");
    process.exit(1);
  }
  // 캐노니컬에서 발행마다 re-vendor (kit 의 사본 갱신) — 편집은 캐노니컬에서.
  if (existsSync(gwReg)) {
    copyFileSync(gwReg, vendored);
    chmodSync(vendored, 0o755);
  }
  copyShWithHeader(regSrc, join(setupDir, "register-clients.sh"), regSrcLabel, orgLabel);
  copied.push("setup/register-clients.sh");

  // 가이드 md — 멤버가 번들에서 바로 읽도록 발행물에 포함 (생성물 헤더 부착, 소스=KIT_ROOT)
  for (const g of ["setup/사용가이드.md", "setup/온보딩.md"]) {
    const src = kitAbs(g);
    if (!existsSync(src)) continue;
    const body = readFileSync(src, "utf8");
    writeFileSync(join(target, g), `<!-- 생성물 — 수정은 workflow-std/${g} 에서 -->\n${body}`);
    copied.push(g);
  }

  // README (한국어 — 배포물 정체 + 사용법 + 경고)
  put("README.md", teamReadme(publishLabel, orgLabel, name));

  // org 표시명 사이드카 — 번들-경로 vendored 설치기가 ~/.lively/org-name 으로 옮긴다(preload 라이브 헤더용).
  put(".lively-org-name", name + "\n");

  // 하네스 라우팅 — dispatchEmit 가 단일/다중("claude,codex") 모두 처리(같은 emit 인터페이스).
  //  각 emit(ctx) 는 {target, orgLabel} 를 받아 발행물에 하네스별 설정을 추가하고 copied 에 push 한다.
  dispatchEmit(harness, { target, orgLabel, copied });

  // 리포트
  const bytes = Buffer.byteLength(art.agentsMd, "utf8");
  const warn = bytes > 32 * 1024 ? "  ⚠️ Codex 32KiB 초과!" : "";
  console.log(`\n✓ 발행 완료 → ${target} (org=${orgLabel}, harness=${harness})`);
  for (const f of copied.sort()) console.log(`  - ${f}`);
  console.log(`  AGENTS.md ${bytes}B (${(bytes / 1024).toFixed(1)} KiB)${warn}`);
  console.log("  ※ git 작업은 publish 가 하지 않음 — 커밋은 오퍼레이터 수행.");
}

// ── 게이트웨이 in-process 키트 번들 (콘텐츠 없는 발행물) ──────────────────────────
// /install 동적 전달용: org-콘텐츠(AGENTS/CLAUDE/MEMORY/org)는 굽지 않고, 멤버 머신 부트스트랩만 조립한다
//  (hooks·settings·setup·register-clients·guides·README·.lively-org-name). materialize/subprocess 불요 —
//  게이트웨이가 in-process import 해 호출하므로 **process.exit 대신 throw**(게이트웨이 프로세스 보호). orgRoot 불필요.
//  publish() 의 kit emit 부분과 동일 알고리즘(콘텐츠 부분만 제거) — 단일 출처 동기화 유지할 것.
export function buildKitBundle(target, { orgName = "조직", orgLabel = "org", harness = "claude" } = {}) {
  const harnessNames = String(harness).split(",").map((h) => h.trim()).filter(Boolean);
  const unknownHarness = harnessNames.filter((h) => !HARNESS_EMIT[h]);
  if (!harnessNames.length || unknownHarness.length) {
    throw new Error(`알 수 없는 harness: ${(unknownHarness.length ? unknownHarness : [harness]).join(", ")} (${Object.keys(HARNESS_EMIT).join("|")})`);
  }
  mkdirSync(target, { recursive: true });
  for (const ent of readdirSync(target)) { // idempotent 클린(.git/members/local.md 보존 — 임시 stage 엔 보통 없음)
    if (ent === ".git") continue;
    if (ent === "members") {
      let subs = null; try { subs = readdirSync(join(target, ent)); } catch { /* */ }
      if (subs) { for (const sub of subs) { if (sub === "local.md") continue; rmSync(join(target, ent, sub), { recursive: true, force: true }); } continue; }
    }
    rmSync(join(target, ent), { recursive: true, force: true });
  }
  const copied = [];
  const put = (rel, content) => { const dest = join(target, rel); mkdirSync(dirname(dest), { recursive: true }); writeFileSync(dest, content); copied.push(rel); };

  // 개인 레이어 견본(KIT template-org) + .gitignore — org-콘텐츠 아님.
  mkdirSync(join(target, "members"), { recursive: true });
  const tplSrc = kitAbs("template-org/members/_template.md");
  if (existsSync(tplSrc)) copyFileSync(tplSrc, join(target, "members/_template.md"));
  else writeFileSync(join(target, "members/_template.md"), "# 개인 레이어 (members/local.md 로 복사해 채우세요)\n\n- 역할:\n- 호칭/말투 선호:\n- 담당 영역:\n");
  copied.push("members/_template.md");
  put(".gitignore", "# 개인 레이어 — 각 머신/사람마다 다르므로 커밋하지 않음\nmembers/local.md\n");

  // setup/ 부트스트랩 스크립트(생성물 헤더, 소스=KIT_ROOT)
  const setupDir = join(target, "setup"); mkdirSync(setupDir, { recursive: true });
  copyShWithHeader(kitAbs("setup/setup-mac.sh"), join(setupDir, "setup-mac.sh"), "kit/setup/setup-mac.sh", orgLabel); copied.push("setup/setup-mac.sh");
  copyShWithHeader(kitAbs("setup/uninstall-mac.sh"), join(setupDir, "uninstall-mac.sh"), "kit/setup/uninstall-mac.sh", orgLabel); copied.push("setup/uninstall-mac.sh");
  copyShWithHeader(kitAbs("setup/update-mac.sh"), join(setupDir, "update-mac.sh"), "kit/setup/update-mac.sh", orgLabel); copied.push("setup/update-mac.sh");
  copyPs1WithHeader(kitAbs("setup/setup-windows.ps1"), join(setupDir, "setup-windows.ps1"), "kit/setup/setup-windows.ps1", orgLabel); copied.push("setup/setup-windows.ps1");
  for (const ps of ["update-windows.ps1", "uninstall-windows.ps1"]) {
    const src = kitAbs("setup/" + ps); if (!existsSync(src)) continue;
    copyPs1WithHeader(src, join(setupDir, ps), "kit/setup/" + ps, orgLabel); copied.push("setup/" + ps);
  }
  // register-clients.sh — 캐노니컬=게이트웨이(context-ontology/scripts), 폴백=vendored.
  //  병합 후 KIT_ROOT=context-ontology/kit 이므로 게이트웨이 디렉토리는 join(KIT_ROOT,"..").
  const gatewayDir = process.env.GATEWAY_DIR || join(KIT_ROOT, "..");
  const gwReg = join(gatewayDir, "scripts", "register-clients.sh");
  const vendored = kitAbs("setup/register-clients.sh");
  const regSrc = existsSync(gwReg) ? gwReg : vendored;
  if (!existsSync(regSrc)) throw new Error(`register-clients.sh 원본 없음: ${gwReg} (vendored 도 없음 — GATEWAY_DIR 확인)`);
  if (existsSync(gwReg)) { copyFileSync(gwReg, vendored); chmodSync(vendored, 0o755); } // 캐노니컬에서 re-vendor
  copyShWithHeader(regSrc, join(setupDir, "register-clients.sh"), existsSync(gwReg) ? "context-ontology/scripts/register-clients.sh" : "kit/setup/register-clients.sh (vendored)", orgLabel);
  copied.push("setup/register-clients.sh");

  // 가이드 md(멤버가 번들에서 바로 읽음)
  for (const g of ["setup/사용가이드.md", "setup/온보딩.md"]) {
    const src = kitAbs(g); if (!existsSync(src)) continue;
    writeFileSync(join(target, g), `<!-- 생성물 — 수정은 kit/${g} 에서 -->\n${readFileSync(src, "utf8")}`); copied.push(g);
  }
  put("README.md", teamReadme(basename(target), orgLabel, orgName));
  put(".lively-org-name", orgName + "\n");

  // 하네스별 부트스트랩(hooks·settings·user-install) — emitClaudeArtifact/emitCodexArtifact(콘텐츠 무관).
  dispatchEmit(harness, { target, orgLabel, copied });
  return { copied };
}

// ── template-org 유틸 (init/check 공용) ──────────────────────────
// 제품 안의 template-org = 새 조직콘텐츠의 1회성 INIT 소스(베이스 아님).
const TEMPLATE_ORG = kitAbs("template-org");

// template-org VERSION 읽기(없으면 "0").
function readTemplateVersion() {
  try { return readFileSync(join(TEMPLATE_ORG, "VERSION"), "utf8").trim() || "0"; }
  catch { return "0"; }
}

// 디렉토리 안의 모든 파일을 상대경로로 나열(.git 제외). 없으면 [].
function listFilesRel(root) {
  const out = [];
  const walk = (dir) => {
    let ents;
    try { ents = readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const e of ents) {
      if (e.name === ".git") continue;
      const abs = join(dir, e.name);
      if (e.isDirectory()) walk(abs);
      else out.push(relative(root, abs));
    }
  };
  walk(root);
  return out.sort();
}

// 디렉토리가 비어있는지(.git 만 있으면 비어있는 것으로 간주 — 새로 git init 한 빈 레포 허용).
function isEmptyish(dir) {
  if (!existsSync(dir)) return true;
  try {
    return readdirSync(dir).filter((e) => e !== ".git" && e !== ".DS_Store").length === 0;
  } catch { return false; }
}

// ── --init <dir>: template-org → 새 독립 조직콘텐츠 레포로 복사 ──
//  비어있지 않으면 거부(--force 로 덮어쓰기 허용 — .git 은 항상 보존).
//  복사 후 .template-version 에 현재 template VERSION 을 스탬프(나중 --check 가 init 버전과 비교).
//  git 은 만들지 않는다(오퍼레이터가 git init/remote). 이후 이 레포는 조직 소유 — template-org 를 다시 당기지 않음.
function initOrg(targetArg, { force = false } = {}) {
  if (!existsSync(TEMPLATE_ORG)) {
    console.error(`✗ template-org 없음: ${TEMPLATE_ORG} — 제품(workflow-std) 레포 안에서 실행하세요.`);
    process.exit(1);
  }
  const target = resolve(process.cwd(), targetArg);
  if (!isEmptyish(target) && !force) {
    console.error(`✗ 대상이 비어있지 않습니다: ${target}`);
    console.error("  덮어쓰려면 --force (.git 은 보존). 보통은 새 빈 디렉토리를 지정하세요.");
    process.exit(1);
  }
  mkdirSync(target, { recursive: true });

  const version = readTemplateVersion();
  // 제품 메타(template-org 자체를 설명) — 새 조직 레포엔 복사하지 않음. VERSION 은 .template-version 스탬프로 대체.
  const TEMPLATE_META = new Set(["VERSION", "CHANGELOG.md", "README.md"]);
  let copied = 0;
  for (const rel of listFilesRel(TEMPLATE_ORG)) {
    if (TEMPLATE_META.has(rel)) continue;
    const dest = join(target, rel);
    mkdirSync(dirname(dest), { recursive: true });
    cpSync(join(TEMPLATE_ORG, rel), dest);
    copied++;
  }
  // init 스탬프 — 이 조직콘텐츠가 어느 template VERSION 에서 출발했는지(doctor 가 신규 옵션 항목 판정에 사용).
  writeFileSync(join(target, ".template-version"), version + "\n");

  console.log(`✓ 새 조직콘텐츠 골격 생성 → ${target}`);
  console.log(`  template-org VERSION ${version} 기준, ${copied}개 파일 복사 + .template-version 스탬프.`);
  console.log("  다음:");
  console.log("   1) org/org-defaults.md — 회사·페르소나·업무방식의 <placeholder> 를 실제 내용으로 채우세요.");
  console.log("   2) org/managed-policy.md — 강제 규칙(짧게). members/ — 사람마다 프로필+신원(email 필수).");
  console.log("   3) gateway-url — 사내 MCP 게이트웨이 주소(없으면 비워둠 — 컨텍스트만, 라이브 데이터 제외).");
  console.log("   4) 점검:  node <workflow-std>/generator/build-context.mjs --check " + targetArg);
  console.log("   5) 발행:  node <workflow-std>/generator/build-context.mjs --org " + targetArg + " --publish <out> --harness claude");
  console.log("  ※ git init/remote/commit 은 이 명령이 하지 않음 — 오퍼레이터가 새 독립 레포로 만듭니다.");
}

// ── --check <org-dir> (doctor): template-org 대비 차이 + 기본 린트 (읽기전용) ──
//  보고: 누락-필수 / init 이후-신규-옵션(template VERSION 비교) / 기본 린트(members email, managed-policy 길이, AGENTS compose 32KiB).
//  종료코드: 누락-필수 또는 린트-에러가 있으면 1, 아니면 0(경고만 있어도 0).
function checkOrg(orgArg) {
  const orgRoot = resolve(process.cwd(), orgArg);
  if (!existsSync(orgRoot)) {
    console.error(`✗ 디렉토리 없음: ${orgRoot}`);
    process.exit(1);
  }
  console.log(`▶ 조직콘텐츠 점검(doctor) → ${orgRoot}`);
  const orgHas = (p) => existsSync(join(orgRoot, p));
  const orgRead = (p) => readFileSync(join(orgRoot, p), "utf8");

  let errors = 0;
  const warn = (m) => console.warn(`  ⚠️ ${m}`);
  const err = (m) => { console.error(`  ✗ ${m}`); errors++; };
  const ok = (m) => console.log(`  ✓ ${m}`);

  // ── 필수: org/org-defaults.md (생성기가 합성할 코어) ──
  if (!orgHas("org/org-defaults.md")) err("필수 누락: org/org-defaults.md (조직 컨텍스트 코어)");
  else ok("org/org-defaults.md 있음");

  // ── 선택 표준 레이어: 없으면 경고(생성기는 스킵하지만 권장) ──
  for (const p of ["org/managed-policy.md", "memory/knowledge-index.md", "members/_template.md"]) {
    if (!orgHas(p)) warn(`선택 누락 → 권장: ${p}`);
  }

  // ── placeholder 미작성 감지(init 직후 상태) ──
  if (orgHas("org/org-defaults.md")) {
    const body = orgRead("org/org-defaults.md");
    if (/<[^>\n]+>/.test(body) || /\bPLACEHOLDER\b/i.test(body)) {
      warn("org/org-defaults.md 에 미작성 <placeholder> 가 남아 있음 — 실제 회사 내용으로 채우세요.");
    }
  }

  // ── template VERSION 비교: init 이후 새로 생긴 옵션 항목 안내 ──
  const curVer = readTemplateVersion();
  let initVer = null;
  try { initVer = readFileSync(join(orgRoot, ".template-version"), "utf8").trim(); } catch { /* 옛 init 또는 수동 생성 */ }
  if (initVer == null) {
    warn(`.template-version 없음 — 이 조직콘텐츠가 어느 template 버전에서 출발했는지 불명(현재 template VERSION=${curVer}). 신규 옵션 필드는 ORG-CONTENT-GUIDE 참고.`);
  } else if (initVer !== curVer) {
    warn(`template VERSION 변동: init=${initVer} → 현재=${curVer}. 새 옵션 필드가 있을 수 있음 → template-org/CHANGELOG.md 를 보고 원하는 것만 opt-in 하세요(강제 아님).`);
  } else {
    ok(`template VERSION 일치(${curVer})`);
  }

  // ── 린트 1: members/*.md frontmatter email (사람 주체는 email = 소스 조인 키) ──
  const membersDir = join(orgRoot, "members");
  if (existsSync(membersDir)) {
    for (const f of readdirSync(membersDir)) {
      if (!f.endsWith(".md") || f.startsWith("_") || f === "local.md") continue;
      const txt = readFileSync(join(membersDir, f), "utf8");
      const fm = txt.match(/^---\n([\s\S]*?)\n---/);
      const kind = fm && /\bkind\s*:\s*human\b/.test(fm[1]);
      const hasEmail = fm && /\bemail\s*:/.test(fm[1]);
      if (kind && !hasEmail) warn(`members/${f}: human 인데 frontmatter 에 email 없음 — email 은 소스 간 조인 키(권장).`);
    }
  }

  // ── 린트 2: managed-policy 길이(최상위 우선순위 항상 로드 — 짧게) ──
  if (orgHas("org/managed-policy.md")) {
    const lines = orgRead("org/managed-policy.md").split("\n").filter((l) => l.trim()).length;
    const bytes = Buffer.byteLength(orgRead("org/managed-policy.md"), "utf8");
    if (bytes > 4096 || lines > 40) warn(`org/managed-policy.md 가 김(${(bytes / 1024).toFixed(1)} KiB, ${lines}줄) — managed-policy 는 짧고 절대적인 규칙만 두세요.`);
    else ok(`managed-policy 분량 적정(${(bytes / 1024).toFixed(1)} KiB)`);
  }

  // ── 린트 3: AGENTS compose 32KiB(Codex 글로벌 인스트럭션 권장 한도) ──
  if (orgHas("org/org-defaults.md")) {
    try {
      const { agentsMd } = generate(orgRoot, { personal: false });
      const bytes = Buffer.byteLength(agentsMd, "utf8");
      if (bytes > 32 * 1024) err(`합성 AGENTS.md 가 32KiB 초과(${(bytes / 1024).toFixed(1)} KiB) — Codex 글로벌 인스트럭션 한도. 분량을 줄이세요.`);
      else ok(`합성 AGENTS.md ${(bytes / 1024).toFixed(1)} KiB (≤32KiB)`);
    } catch (e) {
      err(`합성 시도 실패: ${e.message}`);
    }
  }

  // ── gateway-url 안내(없으면 컨텍스트만, 라이브 데이터 제외 — 에러 아님) ──
  //  파일이 '있어도' 주석/공백뿐이면(init 직후 placeholder) 미작성으로 본다 — 초기화 직후 'green' 오인 방지.
  if (!orgHas("gateway-url")) {
    warn("gateway-url 파일 없음 — 사내 MCP 게이트웨이 주소가 없으면 컨텍스트(파일)만, DB/도메인 라이브 조회는 빠집니다. setup 의 ORG_DEFAULT_URL/McpUrl 로도 줄 수 있습니다.");
  } else {
    const gwLines = orgRead("gateway-url").split(/\r?\n/).map((l) => l.trim()).filter((l) => l && !l.startsWith("#"));
    if (gwLines.length === 0) warn("gateway-url 미작성(주석/공백만) — 실제 게이트웨이 주소를 채우거나 setup 의 ORG_DEFAULT_URL/McpUrl 로 주입하세요(없으면 컨텍스트만).");
  }

  // ── 등록 멤버 존재 안내(init 직후엔 _template/_bindings 만 — '아직 멤버 없음' 명시) ──
  if (existsSync(membersDir)) {
    const realMembers = readdirSync(membersDir).filter((f) => f.endsWith(".md") && !f.startsWith("_") && f !== "local.md");
    if (realMembers.length === 0) warn("아직 등록된 멤버 없음(members/ 에 _template/_bindings 외 실제 사람 파일 없음) — members/_template.md 복사해 사람을 추가하세요.");
  }

  console.log("");
  if (errors) { console.error(`✗ 점검 완료: ${errors}개 에러 — 위 항목을 고치세요.`); process.exit(1); }
  console.log("✓ 점검 완료: 차단 에러 없음(경고는 권장 사항).");
}

// ── CLI ──
// 이 파일을 직접 실행할 때만 CLI 처리(import 시엔 안 돔 — buildStaticContext 재사용용).
const isMain = resolve(process.argv[1] || "") === resolve(fileURLToPath(import.meta.url));
if (isMain) {
  const args = process.argv.slice(2);
  const getOpt = (name) => {
    const i = args.indexOf(name);
    return i !== -1 ? args[i + 1] : null;
  };
  const orgArg = getOpt("--org");
  const pubArg = getOpt("--publish");
  const harness = getOpt("--harness") || "claude";
  const orgNameArg = getOpt("--org-name"); // 표시명 오버라이드(미지정 시 org-defaults.md 에서 도출)
  const emitRootFlag = args.includes("--emit-root");
  const hooksIdx = args.indexOf("--install-hooks");
  const initArg = getOpt("--init");     // 새 조직콘텐츠 골격(template-org → 복사). --org 불요.
  const checkArg = getOpt("--check");   // 조직콘텐츠 점검(doctor). --org 불요. 읽기전용.

  // --init / --check 는 --org 와 독립(템플릿/점검 모드). 먼저 처리하고 종료.
  if (initArg) {
    initOrg(initArg, { force: args.includes("--force") });
    process.exit(0);
  }
  if (checkArg) {
    checkOrg(checkArg); // 내부에서 종료코드 설정(에러 시 exit 1)
    process.exit(0);
  }

  if (!orgArg) {
    console.error("✗ --org <org-content-dir> 가 필요합니다.");
    console.error("  예: node generator/build-context.mjs --org <org-content-dir> --publish <out-dir> --harness claude");
    console.error("  새 조직: --init <dir>  ·  점검: --check <dir>");
    process.exit(1);
  }
  const orgRoot = resolve(process.cwd(), orgArg);
  if (!existsSync(join(orgRoot, "org"))) {
    console.error(`✗ org-content 디렉토리로 보이지 않음(org/ 없음): ${orgRoot}`);
    process.exit(1);
  }

  if (hooksIdx !== -1) {
    // 독푸드/로컬 설치: 각 디렉토리에 emitHooks 만 수행(컨텍스트 md 미발행, 비파괴 머지)
    const dirs = args.slice(hooksIdx + 1).filter((a) => !a.startsWith("--"));
    if (!dirs.length) {
      console.error("✗ 사용법: --install-hooks <dir> [<dir>…]");
      process.exit(1);
    }
    for (const d of dirs) {
      const target = resolve(process.cwd(), d);
      console.log(`▶ 훅 설치 → ${target}`);
      emitHooks(target, basename(orgRoot));
    }
  } else if (pubArg) {
    const target = resolve(process.cwd(), pubArg);
    publish(orgRoot, target, harness, orgNameArg);
    if (emitRootFlag) emitRoot(orgRoot, orgNameArg);
  } else if (emitRootFlag) {
    emitRoot(orgRoot, orgNameArg);
  } else {
    console.error("✗ --publish <out-dir> 또는 --install-hooks 또는 --emit-root 중 하나가 필요합니다.");
    process.exit(1);
  }
}
