#!/usr/bin/env node
// grok 배선 사양테스트(#1701) — [[delivery-install-invariants]] 의 **비파괴·멱등·라운드트립**을
//  grok(hook-file + config.toml 센티넬 배선)에 적용해 고정한다. codex/opencode/antigravity 판과 같은 구조:
//  실제 설치기/제거기를 돌려 산출 파일을 본다. 오프라인·fs-only: 샌드박스 HOME(LIVELY_HOME) 안에서만 읽고 쓴다.
//  ⚠ 이 머신엔 **실제 grok 설치(~/.grok)** 가 있다 — ⓪ 지문 대조가 특히 실질적이다.
//  실행: node kit/setup/grok-wiring.test.mjs   (kit/**/*.test.mjs 라 npm test 체인에 자동 포함)
//
//  엣지 표(GW1~GW10)는 <스크래치패드>/spec-grok-wiring.md — 케이스 이름의 [GW#] 가 그 행 번호다.
import { mkdtempSync, rmSync, mkdirSync, cpSync, readFileSync, writeFileSync, existsSync, lstatSync, readdirSync } from "node:fs";
import { tmpdir, homedir } from "node:os";
import { join, dirname } from "node:path";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { fileURLToPath, pathToFileURL } from "node:url";

const KIT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SANDBOX = mkdtempSync(join(tmpdir(), "grok-wiring-test-"));
const BUNDLE = join(SANDBOX, "bundle");
const HOME = join(SANDBOX, "home");
const GROK = join(HOME, ".grok");
const HOOKSFILE = join(GROK, "hooks", "lively-grok.json");
const CFG = join(GROK, "config.toml");
const RULES = join(GROK, "rules", "lively.md");
const CLAUDE_SETTINGS = join(HOME, ".claude", "settings.json");
const GRK_BEGIN = "# >>> lively-managed (auto-generated by workflow-std/adapters/grok — do not edit) >>>";
const EVENTS = ["SessionStart", "SessionEnd", "UserPromptSubmit", "PreToolUse", "PostToolUse", "Stop", "Notification", "SubagentStop", "PreCompact", "PostCompact"];

let pass = 0, fail = 0;
const ok = (n) => { pass++; console.log(`ok  ${n}`); };
const bad = (n, why) => { fail++; console.error(`FAIL ${n} — ${why}`); };
const digest = (p) => { try { return createHash("sha256").update(readFileSync(p)).digest("hex"); } catch { return "(none)"; } };
const readJson = (p) => { try { return JSON.parse(readFileSync(p, "utf8")); } catch { return null; } };

// ⓪ 배선 단언 [GW9] — 실 ~/.grok 무접촉(이 머신의 실제 grok 설치 지문).
const REAL_CFG = join(homedir(), ".grok", "config.toml");
const REAL_BEFORE = digest(REAL_CFG);

// ── 발행물 번들(publish() 배치 최소 재현) ────────────────────────────────────
const { HOOK_SCRIPTS: HOOKS } = await import(pathToFileURL(join(KIT, "setup", "user-install.mjs")).href);
function makeBundle({ autoApprove = ["mcp__lively__whoami", "mcp__lively__knowledge_get"], withAdapter = true } = {}) {
  rmSync(BUNDLE, { recursive: true, force: true });
  mkdirSync(join(BUNDLE, ".claude", "hooks"), { recursive: true });
  mkdirSync(join(BUNDLE, ".lively"), { recursive: true });
  mkdirSync(join(BUNDLE, "setup"), { recursive: true });
  mkdirSync(join(BUNDLE, "cli"), { recursive: true });
  for (const h of HOOKS) {
    // [GW8] 구버전 번들 흉내 — grok-adapter.mjs 만 빠진 번들. ⚠ 설치기는 HOOK_SCRIPTS 누락 시 **중단**하므로
    //  (부분 설치 금지 — AW10 과 같은 계약) 여기선 파일을 복사하되 설치 후 ~/.lively/hooks 에서 지워 흉내낸다.
    cpSync(join(KIT, "hooks", h), join(BUNDLE, ".claude", "hooks", h));
  }
  for (const f of ["user-install.mjs", "user-uninstall.mjs", "host-effects.mjs", "work.mjs", "work-roots-header.mjs"]) cpSync(join(KIT, "setup", f), join(BUNDLE, "setup", f));
  for (const f of ["lively.mjs", "lively-mcp-gateway.mjs"]) cpSync(join(KIT, "cli", f), join(BUNDLE, "cli", f));
  writeFileSync(join(BUNDLE, ".lively-org-name"), "테스트조직\n");
  writeFileSync(join(BUNDLE, ".lively", "auto-approve.json"), JSON.stringify({ allow: autoApprove }));
  writeFileSync(join(BUNDLE, ".lively", "mcp-servers.json"), JSON.stringify({ servers: [] }));
  void withAdapter;
}
function freshHome({ userConfig = null, userHook = null } = {}) {
  rmSync(HOME, { recursive: true, force: true });
  mkdirSync(join(HOME, ".lively"), { recursive: true });
  writeFileSync(join(HOME, ".lively", "gateway-url"), "http://127.0.0.1:9\n"); // 토큰 없음 = 네트워크 미접촉
  if (userConfig !== null) { mkdirSync(dirname(CFG), { recursive: true }); writeFileSync(CFG, userConfig); }
  if (userHook !== null) { mkdirSync(join(GROK, "hooks"), { recursive: true }); writeFileSync(join(GROK, "hooks", "user-own.json"), userHook); }
}
// [GW9] LIVELY_HOME 격리가 GROK_HOME 을 무시하는지 — 설치마다 미끼 GROK_HOME 을 함께 준다.
const DECOY = join(SANDBOX, "decoy-grok-home");
function install({ expectFail = false } = {}) {
  const r = spawnSync(process.execPath, [join(BUNDLE, "setup", "user-install.mjs"), "--harness", "grok", "--clone-root", BUNDLE],
    { env: { ...process.env, LIVELY_HOME: HOME, GROK_HOME: DECOY }, encoding: "utf8" });
  if (!expectFail && r.status !== 0) throw new Error(`설치기 exit=${r.status}\n${r.stderr || r.stdout}`);
  return `${r.stdout}${r.stderr}`;
}
function uninstall({ dry = false, member = false } = {}) {
  const args = member
    ? [join(KIT, "setup", "user-uninstall.mjs"), "--harness", "grok", "--yes"]
    : [join(KIT, "adapters", "grok", "uninstall.mjs")];
  if (dry) args.push("--dry-run");
  const r = spawnSync(process.execPath, args, { env: { ...process.env, LIVELY_HOME: HOME, GROK_HOME: DECOY }, encoding: "utf8" });
  return `${r.stdout}${r.stderr}`;
}

// ── GW1/GW2 기본 설치 ────────────────────────────────────────────────────────
makeBundle();
freshHome();
install();
{
  // [GW1] 훅 파일 — 정규 파일(비심링크: grok 은 심링크 훅 파일을 **무음 스킵**한다), 10이벤트, 어댑터 command.
  const isReg = existsSync(HOOKSFILE) && !lstatSync(HOOKSFILE).isSymbolicLink();
  const doc = readJson(HOOKSFILE);
  const evs = doc?.hooks ? Object.keys(doc.hooks) : [];
  const allEvents = EVENTS.every((e) => evs.includes(e)) && evs.length === EVENTS.length;
  let cmdOk = allEvents;
  for (const e of evs) {
    for (const grp of doc.hooks[e] || []) {
      for (const h of grp.hooks || []) {
        if (h.type !== "command" || !h.command.includes("grok-adapter.mjs") || !h.command.endsWith(` ${e}`) || typeof h.timeout !== "number") cmdOk = false;
      }
    }
  }
  (isReg && allEvents && cmdOk)
    ? ok("GW1 설치 → lively-grok.json(정규 파일·10이벤트·어댑터 command+이벤트 argv·type/timeout)")
    : bad("GW1 훅 파일", `정규=${isReg} 이벤트=${JSON.stringify(evs)} cmd=${cmdOk}`);

  // [GW2] config.toml 센티넬 — MCP stdio 프록시 + stamp. [permission] 공유 테이블 금지(사용자 config 재정의 충돌).
  const t = readFileSync(CFG, "utf8");
  const okSentinel = t.includes(GRK_BEGIN) && t.includes("# <<< lively-managed <<<");
  const okMcp = /\[mcp_servers\.lively\]\ncommand = "[^"]+"\nargs = \["mcp"\]/.test(t) && /\[mcp_servers\.lively\.env\]\nLIVELY_HARNESS = "grok"/.test(t);
  const noPermTable = !/^\s*\[permission\]/m.test(t);
  (okSentinel && okMcp && noPermTable)
    ? ok("GW2 config.toml 센티넬(MCP stdio+stamp) + [permission] 테이블 없음")
    : bad("GW2 config.toml", `센티넬=${okSentinel} mcp=${okMcp} perm없음=${noPermTable}`);

  // [GW2b] auto-approve 채널 — grok 은 ~/.claude/settings.json permissions 를 compat 로 읽는다(#1701 실측).
  const allow = readJson(CLAUDE_SETTINGS)?.permissions?.allow ?? [];
  (allow.includes("mcp__lively__whoami") && allow.includes("mcp__lively__knowledge_get"))
    ? ok("GW2b auto-approve → 샌드박스 ~/.claude/settings.json permissions.allow 반영(compat 채널)")
    : bad("GW2b auto-approve", JSON.stringify(allow));

  // [GW3] 오프라인 — rules/lively.md 미생성 + 보류 안내(첫 성공 세션/업데이트가 채운다 — 설계 결정).
  !existsSync(RULES) ? ok("GW3 오프라인 설치 — rules/lively.md 미생성(보류)") : bad("GW3 오프라인", "rules 가 생겼다(무엇으로?)");
}

// ── GW5 멱등 — 두 번째 설치가 **바이트 동일** ────────────────────────────────
{
  const before = digest(HOOKSFILE) + "||" + digest(CFG) + "||" + digest(CLAUDE_SETTINGS);
  install();
  const after = digest(HOOKSFILE) + "||" + digest(CFG) + "||" + digest(CLAUDE_SETTINGS);
  const sentinels = (readFileSync(CFG, "utf8").match(new RegExp(GRK_BEGIN.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "g")) || []).length;
  (before === after && sentinels === 1)
    ? ok("GW5 설치 멱등(2회 실행 결과 바이트 동일 · 센티넬 1개)")
    : bad("GW5 멱등", `동일=${before === after} 센티넬=${sentinels}개`);
}

// ── GW4 사용자 설정·사용자 훅 파일 불가침 ────────────────────────────────────
const USER_CFG = '[ui]\npermission_mode = "auto"\n\n[mcp_servers.mine]\ncommand = "/usr/bin/true"\n';
{
  makeBundle();
  freshHome({ userConfig: USER_CFG, userHook: '{ "hooks": { "Stop": [ { "hooks": [ { "type": "command", "command": "echo mine" } ] } ] } }' });
  const userHookDigest = digest(join(GROK, "hooks", "user-own.json"));
  install();
  const t = readFileSync(CFG, "utf8");
  const userKept = t.includes('permission_mode = "auto"') && t.includes("[mcp_servers.mine]") && t.includes(GRK_BEGIN);
  const hookKept = digest(join(GROK, "hooks", "user-own.json")) === userHookDigest;
  (userKept && hookKept)
    ? ok("GW4 사용자 config 키·사용자 훅 파일 불가침 + 우리 블록만 추가")
    : bad("GW4 불가침", `config보존=${userKept} 훅보존=${hookKept}`);
}

// ── GW7 라운드트립 — member 제거기(user-uninstall) 가 우리 것만 걷는다 ────────
{
  const out = uninstall({ member: true });
  const t = existsSync(CFG) ? readFileSync(CFG, "utf8") : "";
  const ourGone = !existsSync(HOOKSFILE) && !t.includes(GRK_BEGIN) && !existsSync(RULES);
  const userKept = t.includes('permission_mode = "auto"') && t.includes("[mcp_servers.mine]");
  const userHookKept = existsSync(join(GROK, "hooks", "user-own.json"));
  (ourGone && userKept && userHookKept && /grok/i.test(out))
    ? ok("GW7 member 제거 — 훅 파일·센티넬 제거, 사용자 config·훅 보존")
    : bad("GW7 라운드트립", `우리것제거=${ourGone} 사용자보존=${userKept} 사용자훅=${userHookKept}`);
}

// ── GW7b 우리 블록뿐이던 config 는 제거 시 파일째 정리(설치전상태=파일없음 복구) ──
{
  makeBundle();
  freshHome();
  install();
  uninstall({ member: true });
  (!existsSync(CFG) && !existsSync(HOOKSFILE))
    ? ok("GW7b 우리 블록뿐이던 config.toml 은 제거 시 파일째 정리")
    : bad("GW7b 파일 정리", `cfg잔존=${existsSync(CFG)} hooks잔존=${existsSync(HOOKSFILE)}`);
}

// ── GW7c 어댑터 경로 제거기(adapters/grok/uninstall.mjs)도 같은 결과 ──────────
{
  makeBundle();
  freshHome({ userConfig: USER_CFG });
  install();
  uninstall();
  const t = existsSync(CFG) ? readFileSync(CFG, "utf8") : "";
  (!existsSync(HOOKSFILE) && !t.includes(GRK_BEGIN) && t.includes("[mcp_servers.mine]"))
    ? ok("GW7c 어댑터 경로 제거기도 같은 결과(훅·센티넬 제거+사용자 보존)")
    : bad("GW7c 어댑터 제거", `hooks잔존=${existsSync(HOOKSFILE)} 센티넬잔존=${t.includes(GRK_BEGIN)}`);
}

// ── GW6 사용자 영역 [mcp_servers.lively] 충돌 — 머지 건너뜀+경고, 무수정 ──────
{
  makeBundle();
  const conflict = '[mcp_servers.lively]\ncommand = "/my/own/lively"\n';
  freshHome({ userConfig: conflict });
  const before = digest(CFG);
  const out = install();
  (digest(CFG) === before && /충돌.*건너뜀|건너뜀.*충돌/.test(out.replace(/\n/g, " ")))
    ? ok("GW6 사용자 [mcp_servers.lively] 충돌 — 머지 건너뜀+경고(무수정)")
    : bad("GW6 충돌", `무수정=${digest(CFG) === before}`);
  // 훅 파일은 충돌과 무관하게 배선된다(MCP 충돌이 거버넌스까지 막으면 안 된다).
  existsSync(HOOKSFILE) ? ok("GW6b MCP 충돌이어도 훅 배선은 진행") : bad("GW6b 훅 배선", "미설치");
}

// ── GW8 (신규 도입물 부재 행) 어댑터가 설치 자리에 없으면 — 훅 파일 미생성+경고, MCP 는 진행 ──
{
  makeBundle();
  freshHome();
  // 설치기는 번들 누락 시 아예 중단하므로(부분 설치 금지 — 그 계약은 AW10/설치기 공용 케이스가 지킨다),
  //  "어댑터 없는 설치 자리"는 1차 설치 후 ~/.lively/hooks 에서 어댑터만 지우고 재설치해 흉내낸다
  //  (실제 시나리오: 구버전 번들로 자가 업데이트된 뒤 grok 배선만 다시 도는 경우).
  install();
  rmSync(join(HOME, ".lively", "hooks", "grok-adapter.mjs"), { force: true });
  rmSync(HOOKSFILE, { force: true });
  // 번들에서도 어댑터를 빼서 재복사가 못 채우게 한다 — 단 설치기 중단을 피하려고 HOOK_SCRIPTS 검사 전에
  //  이미 복사된 상태를 재현할 수 없으므로, 여기선 번들에 어댑터가 있으면 ~/.lively 에 다시 깔린다.
  //  그래서 이 행은 **설치기 산출물이 아니라 installGrok 의 가드**를 본다: 어댑터 부재 시 훅 파일을 쓰지 않는가.
  //  번들에서 어댑터를 지우면 설치기가 중단하므로(HOOK_SCRIPTS 완전성), 그 중단 자체를 단언한다.
  rmSync(join(BUNDLE, ".claude", "hooks", "grok-adapter.mjs"), { force: true });
  const out = install({ expectFail: true });
  (/누락/.test(out) && !existsSync(HOOKSFILE))
    ? ok("GW8 어댑터 빠진 번들 — 설치 중단(부분 설치 금지) · 훅 파일 미생성")
    : bad("GW8 구버전 번들", `hooks생성=${existsSync(HOOKSFILE)} out=${out.slice(0, 120)}`);
}

// ── GW10 kit 오케스트레이터 감지 — 실제 `setup/uninstall.mjs` 경로가 grok 을 다룬다 ──
{
  makeBundle();
  freshHome();
  install();
  const r = spawnSync(process.execPath, [join(KIT, "setup", "uninstall.mjs"), "--dry-run", "--harness", "grok"],
    { env: { ...process.env, LIVELY_HOME: HOME, GROK_HOME: DECOY }, encoding: "utf8" });
  const out = `${r.stdout}${r.stderr}`;
  (r.status === 0 && /grok/i.test(out) && /lively-grok\.json/.test(out))
    ? ok("GW10 kit 오케스트레이터가 grok 을 감지·제거 계획에 포함(dry-run)")
    : bad("GW10 오케스트레이터", `exit=${r.status} out=${out.slice(0, 200)}`);
}

// ── ⓪ 재검 [GW9] ────────────────────────────────────────────────────────────
{
  digest(REAL_CFG) === REAL_BEFORE
    ? ok("⓪ 실 ~/.grok/config.toml 무접촉(이 머신의 실제 grok 설치 보호)")
    : bad("⓪ 실 홈 무접촉", "샌드박스 계약 파손 — 실 ~/.grok 이 변경됨");
  // LIVELY_HOME 격리 시 GROK_HOME(미끼) 무시 — 디렉터리가 아예 안 생겼어야 한다.
  //  (grok 쪽 OnceLock 과 달리 우리 설치기는 매 실행 env 를 읽으므로, 여기 새면 테스트가 실 GROK_HOME 을 오염시킨다.)
  const decoyTouched = existsSync(DECOY) && readdirSync(DECOY).length > 0;
  !decoyTouched ? ok("⓪b LIVELY_HOME 격리가 GROK_HOME env 를 무시(미끼 디렉터리 무접촉)")
    : bad("⓪b GROK_HOME 격리", `미끼에 파일이 생겼다: ${readdirSync(DECOY).join(",")}`);
}

rmSync(SANDBOX, { recursive: true, force: true });
console.log(`\n${fail ? "✗" : "✓"} grok-wiring: ${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
